# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Habilidades
    url: '/#skills-1'
    weight: 20
  - name: Posts
    url: '#posts'
    weight: 55
  - name: Projetos
    url: '#projects'
    weight: 50
  - name: Aulas
    url: '#aulas'
    weight: 40
  - name: Análises de dados
    url: '#scripts'
    weight: 45
  # - name: Agenda
  #   url: '/#schedule/'
  #   weight: 51
  # - name: Contato
  #   url: '#contact'
  #   weight: 60
  - name: Ementa
    url: uploads/ementa.pdf
    weight: 70
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.

