---
title: "Cronograma da disciplina"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

Esta página contém um esboço dos tópicos, conteúdos e tarefas para o semestre. Este cronograma será atualizado conforme o semestre avança.

<!-- https://fontawesome.com/search?o=r&m=free -->
<!-- https://jpswalsh.github.io/academicons/ -->


<!-- [{{< fa file-pdf size=2xl >}}](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  |  [️](/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |       [{{< fa laptop-file size=2xl >}}](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"} -->

<!-- {{< fa brands r-project size=2xl >}}  -  scripts -->
<!-- {{< fa file-powerpoint size=2xl >}}   -  slides -->
<!-- {{< fa laptop-file size=2xl >}}  -  estudo de caso -->
<!-- {{< fa file-pdf size=2xl >}}  -  artigo -->
<!-- {{< fa table size=2xl >}}  -  tabelas estatisticas -->
<!-- {{< fa-solid fa-file-lines size=2xl >}}  -  exercicios -->

::: column-screen-inset-right
| Semana | Data | Tópico | Artigo | Slides |EC |LE |Script  | Avaliação | Projeto |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|  [1](programacao/semana-1.html)  | Ter, 06/05 | Apresentação da disciplina |  |  |  |  | | 
|  | Qui, 08/05 | Não haverá aula | |  | | | | | |
|  [2](programacao/semana-2.html)  | Ter, 13/05 | Conceitos iniciais | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Conceitos%20iniciais/conceitos_iniciais.html "Conceitos iniciais"){aria-label="Conceitos iniciais"} | | | | | | 
|  | Qui, 15/05 | Conceitos iniciais | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Conceitos%20iniciais/conceitos_iniciais.html#/importância-da-definição-dos-objetivos "Conceitos iniciais"){aria-label="Conceitos iniciais"} | | | | | | 
|  [3](programacao/semana-3.html)  | Ter, 20/05 | Pré-processamento de dados | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Pre_processamento/pre_processamento.html#/processo-de-preparação-da-base-de-dados "Pré-processamento"){aria-label="Pré-processamento"} | | | | | | 
|                           | Qui, 22/05 | Não haverá aula! |  |   | |  |   [{{< fa brands r-project size=2xl >}}](analise_dados/data_science.html "Script análise de dados"){aria-label="Script análise de dados"} ||
|  [4](programacao/semana-4.html)  | Ter, 27/05 | Pré-processamento de dados | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Pre_processamento/pre_processamento.html#/tratamento-de-valores-inconsistentes "Pré-processamento"){aria-label="Pré-processamento"} | | | | | | 
|                           | Qui, 29/05 | Pré-processamento de dados |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/Pre_processamento/pre_processamento.html#/tratamento-de-valores-inconsistentes "Pré-processamento"){aria-label="Pré-processamento"}  | |  |   ||

<!-- |  [4](programacao/semana-4.html)  | Seg, 02/12 | Relato (Série) de casos | [{{< fa file-pdf size=2xl >}}](artigos/relato_de_caso_coronavirus_coracao.pdf) | [{{< fa file-powerpoint size=2xl >}}️](/aulas/Planejamento/index.html "Relato e Séries de casos"){aria-label="Relato e Séries de casos"}    |  |  ||    -->
<!-- |                           | Qua, 04/11 | Estudos de coorte | [{{< fa file-pdf size=2xl >}}](artigos/impacto_funcionalidade_idosos_estudo_coorte.pdf) | [{{< fa file-powerpoint size=2xl >}}️](/aulas/Planejamento/#/estudos-observacionais-analíticos "Estudos de coorte"){aria-label="Estudos de coorte"}  |  |  |  |  |   -->
<!-- |  [5](programacao/semana-5.html)  | Seg, 09/12 | Não haverá aula! (Encontro de Saberes) |  | |  |  ||    -->
<!-- |                           | Qua, 11/12 | Não haverá aula! (Encontro de Saberes) |  |  |  |  |  |  |   -->
<!-- |  [6](programacao/semana-6.html)  | Seg, 16/12 | Estudos caso-controle | [{{< fa file-pdf size=2xl >}}](artigos/fatores_cancer_boca_caso_controle.pdf) | [{{< fa file-powerpoint size=2xl >}}️](/aulas/Planejamento/#/estudo-caso-controle  "Estudos caso-controle"){aria-label="Estudos caso-controle"}    |  |  || -->
<!-- |                           | Qua, 18/12 | Não haverá aula!  |  |  |  |  |  |  |  -->
<!-- |     | 23/12 a 19/01  | Recesso Acadêmico |         |  | | | | | -->
<!-- |  [7](programacao/semana-7.html)  | Seg, 20/01 | Estudos Transversais | [{{< fa file-pdf size=2xl >}}](artigos/Prevalência_fatores_associados_bruxismo_estudo_transversal.pdf) | [{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Planejamento/#/estudos-transversais "Estudos transversais"){aria-label="Estudos transversais"}  |  |  |  |  | -->
<!-- |                           | Qua, 22/01 | Estudos Ecológicos | [{{< fa file-pdf size=2xl >}}](artigos/Aumento_das_internações_por_síndrome_de_Guillain-Barré_no_Brasil_estudo_ecológico.pdf) | [{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Planejamento/#estudos-ecológicos "Estudos ecológicos"){aria-label="Estudos ecológicos"}  |  |  |  |  | -->
<!-- |  [8](programacao/semana-8.html)  | Seg, 27/01 | Ensaios clínicos aleatorizados | [{{< fa file-pdf size=2xl >}}](artigos/Administração orofaríngea de colostro em recém-nascidos com gastrosquise_ensaio clínico randomizado.pdf) | [{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Planejamento/#estudos-experimentais "Ensaios Clínicos Aleatorizados"){aria-label="Ensaios Clínicos Aleatorizados"}  |  |  |  |  | -->
<!-- |                           | Qua, 29/01 | Não haverá aula!  |  |  |  |  |  |  | -->
<!-- |  [9](programacao/semana-9.html)  | Seg, 03/02 | Não haverá aula! |   |  |  | [{{< fa file-lines size=2xl >}}️   ](/exercicios/lista01.html "Lista de Exercícios 01"){aria-label="Lista de Exercícios 01"}   |  | -->
<!-- |                           | Qua, 05/02 | Outros tipos de estudos  |  |[{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Planejamento/#outros-tipos-de-estudo "Outros tipos de estudo"){aria-label="Outros tipos de estudo"}   |  |  |  |  | -->
<!-- |  [10](programacao/semana-10.html)  | Seg, 10/02 | Ensaios clínicos no R |   |[{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Planejamento/ensaios_no_R.html "Ensaios clínicos no R"){aria-label="Ensaios clínicos no R"}   |[ {{< fa laptop-file size=2xl >}}](estudos_de_casos/estudo03.html "Estudo de caso 03"){aria-label="Estudo de caso 03"}   | |[{{< fa brands r-project size=2xl >}}](/analise_dados/ensaio_clinico.html "Script análise de dados"){aria-label="Script análise de dados"}    | -->
<!-- |                           | Qua, 12/02 | Testes diagnósticos  |[{{< fa file-pdf size=2xl >}}](/artigos/Entendendo os testes diagnósticos_P1.pdf)  |[{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Testes%20diagnósticos/testesDiagnosticos.html "Testes diagnósticos"){aria-label="Testes diagnósticos"}   |  |  |  |  | -->
<!-- |  [11](programacao/semana-11.html)  | Seg, 17/02 | Prof. Eduardo Bearzoti | [{{< fa file-pdf size=2xl >}}](/Material Prof Eduardo Bearzoti/Artigo_Original.pdf)  |[{{< fa file-powerpoint size=2xl >}}](/Material Prof Eduardo Bearzoti/Seminario1_Cad.pdf "Razão de chances: Aplicações na área da saúde"){aria-label="Razão de chances: Aplicações na área da saúde"}   |[ {{< fa laptop-file size=2xl >}}](/Material Prof Eduardo Bearzoti/Estudo_Caso_Interpretacao.pdf "Estudo de caso"){aria-label="Estudo de caso"}   | |   | -->
<!-- |                           | Qua, 19/02 | Prof. Eduardo Bearzoti |   |[{{< fa file-powerpoint size=2xl >}}](/Material Prof Eduardo Bearzoti/Seminario2_Cad.pdf "Estudos de Casos na Área da Saúde"){aria-label="Estudos de Casos na Área da Saúde"}   |[ {{< fa laptop-file size=2xl >}}](/Material Prof Eduardo Bearzoti/Relatorio_COVID.pdf "Estudo de caso"){aria-label="Estudo de caso"}   | |   | -->
<!-- |  [12](programacao/semana-12.html)  | Seg, 24/02 | Testes diagnósticos | [{{< fa file-pdf size=2xl >}}](artigos/Teste Rapido para Deteccao da Infeccao pelo HIV-1 em Gestantes.pdf)  |[{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Testes%20diagnósticos/testesDiagnosticos.html#/valor-de-predição-de-um-teste "Testes diagnósticos"){aria-label="Testes diagnósticos"}   |   | |   | -->
<!-- |                           | Qua, 26/02 | Testes diagnósticos |   |[{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Testes%20diagnósticos/testesDiagnosticos.html#/combinação-em-paralelo "Testes diagnósticos"){aria-label="Testes diagnósticos"}   |    | [{{< fa file-lines size=2xl >}}️   ](/exercicios/lista02.html "Lista de Exercícios 02"){aria-label="Lista de Exercícios 02"}|   | -->
<!-- |     | Seg, 03/03 | Carnaval  |  |  |  |  |  |  |  -->
<!-- |     | Qua, 05/03  | Carnaval |         |  | | | | | -->
<!-- |  [13](programacao/semana-13.html)  | Seg, 10/03 | Não haverá aula! |   |   |   | |   | -->
<!-- |                           | Qua, 12/03 |  Não haverá aula! |   |   |   | |   | -->
<!-- |  [14](programacao/semana-14.html)  | Seg, 17/03 | Testes diagnósticos no R |   |[{{< fa file-powerpoint size=2xl >}}️   ](/aulas/Testes%20diagnósticos/testes_R.html "Testes diagnósticos no R"){aria-label="Testes diagnósticos no R"}   |  [ {{< fa laptop-file size=2xl >}}](estudos_de_casos/estudo04.html "Estudo de caso 04"){aria-label="Estudo de caso 04"}  | |  [{{< fa brands r-project size=2xl >}}](/analise_dados/teste_diabetes.html "Script análise de dados"){aria-label="Script análise de dados"} | -->
<!-- |                           | Qua, 20/03 |  Modelos de regressão logística e riscos proporcionais |[{{< fa file-pdf size=2xl >}}](/artigos/Fatores associados à obesidade em idosos.pdf)   |[{{< fa file-powerpoint size=2xl >}}️   ](/aulas/ModeloLogistico_cox/logistico_cox.html#/title-slide "Modelos logístico e riscos proporcionais"){aria-label="Modelos logístico e riscos proporcionais"}   |    | |   | -->
<!-- |  [15](programacao/semana-15.html)  | Seg, 24/03 |  Modelos de regressão logística e riscos proporcionais |[{{< fa file-pdf size=2xl >}}](/artigos/Uso da regressão de Cox para estimar fatores associados a óbito.pdf)   |[{{< fa file-powerpoint size=2xl >}}️   ](/aulas/ModeloLogistico_cox/logistico_cox.html#/modelo-de-riscos-proporcionais-cox "Modelos logístico e riscos proporcionais"){aria-label="Modelos logístico e riscos proporcionais"}   |    | |   | -->
<!-- |                           | Qua, 27/03 |  Não haverá aula! |   |   |    | |   | -->
:::

```{r echo = FALSE}
knitr::knit_exit()
```

