<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Reconhecendo padrões usando a base de dados Space Titanic – EST125 - Introdução à Mineração de Dados</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-748b535e376f14d4692bf2b2e5fd6380.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b09848b6287391c45069fed345a57cb2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-e9f3ba5fbee03b112b18b9666ab66a2c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-b09848b6287391c45069fed345a57cb2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="Reconhecendo padrões usando a base de dados Space Titanic – EST125 - Introdução à Mineração de Dados">
<meta property="og:description" content="Homepage da disciplina EST125 - Introdução à Mineração de Dados, 2026/1.">
<meta property="og:image" content="http://professortp.com.br/est125/analise_dados/space_titanic_cluster_files/figure-html/unnamed-chunk-9-1.png">
<meta property="og:site_name" content="EST125 - Introdução à Mineração de Dados">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Reconhecendo padrões usando a base de dados Space Titanic</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://github.com/tiagomartin/est125" title="github" class="quarto-navigation-tool px-1" aria-label="github"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aulas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análises de Dados</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cronograma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cronograma da Disciplina</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../plano.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plano de Ensino</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projeto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projeto Avaliativo</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#pacotes-utilizados" id="toc-pacotes-utilizados" class="nav-link active" data-scroll-target="#pacotes-utilizados">Pacotes utilizados</a></li>
  <li><a href="#leitura-dos-dados" id="toc-leitura-dos-dados" class="nav-link" data-scroll-target="#leitura-dos-dados">Leitura dos dados</a></li>
  <li><a href="#receita-de-pré-processamento" id="toc-receita-de-pré-processamento" class="nav-link" data-scroll-target="#receita-de-pré-processamento">Receita de pré-processamento</a></li>
  <li><a href="#pré-processamento-fora-do-tuning" id="toc-pré-processamento-fora-do-tuning" class="nav-link" data-scroll-target="#pré-processamento-fora-do-tuning">Pré-processamento fora do tuning</a></li>
  <li><a href="#verificando-a-estrutura-de-agrupamento-com-pca" id="toc-verificando-a-estrutura-de-agrupamento-com-pca" class="nav-link" data-scroll-target="#verificando-a-estrutura-de-agrupamento-com-pca">Verificando a Estrutura de Agrupamento com PCA</a></li>
  <li><a href="#definição-dos-modelos-k-means-e-hierárquico" id="toc-definição-dos-modelos-k-means-e-hierárquico" class="nav-link" data-scroll-target="#definição-dos-modelos-k-means-e-hierárquico">Definição dos modelos K-means e Hierárquico</a></li>
  <li><a href="#tuning-com-validação-cruzada" id="toc-tuning-com-validação-cruzada" class="nav-link" data-scroll-target="#tuning-com-validação-cruzada">Tuning com validação cruzada</a></li>
  <li><a href="#resultados-e-melhor-modelo" id="toc-resultados-e-melhor-modelo" class="nav-link" data-scroll-target="#resultados-e-melhor-modelo">Resultados e melhor modelo</a></li>
  <li><a href="#visualização-de-grupos-gerados-via-pca" id="toc-visualização-de-grupos-gerados-via-pca" class="nav-link" data-scroll-target="#visualização-de-grupos-gerados-via-pca">Visualização de Grupos Gerados via PCA</a></li>
  <li><a href="#tuning-manual-de-dbscan-meanshift-e-som" id="toc-tuning-manual-de-dbscan-meanshift-e-som" class="nav-link" data-scroll-target="#tuning-manual-de-dbscan-meanshift-e-som">Tuning manual de DBSCAN, MeanShift e SOM</a>
  <ul class="collapse">
  <li><a href="#tuning-de-dbscan" id="toc-tuning-de-dbscan" class="nav-link" data-scroll-target="#tuning-de-dbscan">Tuning de DBSCAN</a></li>
  <li><a href="#tuning-de-meanshift" id="toc-tuning-de-meanshift" class="nav-link" data-scroll-target="#tuning-de-meanshift">Tuning de MeanShift</a></li>
  <li><a href="#tuning-de-redes-som-kohonen" id="toc-tuning-de-redes-som-kohonen" class="nav-link" data-scroll-target="#tuning-de-redes-som-kohonen">Tuning de Redes SOM (Kohonen)</a></li>
  </ul></li>
  <li><a href="#análise-dos-clusters" id="toc-análise-dos-clusters" class="nav-link" data-scroll-target="#análise-dos-clusters">Análise dos Clusters</a></li>
  <li><a href="#validação-estatística-dos-agrupamentos" id="toc-validação-estatística-dos-agrupamentos" class="nav-link" data-scroll-target="#validação-estatística-dos-agrupamentos">Validação Estatística dos Agrupamentos</a></li>
  <li><a href="#perfis-dos-grupos-gerados" id="toc-perfis-dos-grupos-gerados" class="nav-link" data-scroll-target="#perfis-dos-grupos-gerados">Perfis dos grupos gerados</a>
  <ul class="collapse">
  <li><a href="#interpretação-geral-dos-grupos" id="toc-interpretação-geral-dos-grupos" class="nav-link" data-scroll-target="#interpretação-geral-dos-grupos">Interpretação geral dos grupos</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/tiagomartin/est125/edit/main/analise_dados/space_titanic_cluster.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/tiagomartin/est125/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Reconhecendo padrões usando a base de dados Space Titanic</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Imagine que você é um cientista de dados responsável por entender os perfis dos passageiros da nave Space Titanic, que viajava em direção a uma colônia espacial. Infelizmente, parte da tripulação desapareceu misteriosamente e agora queremos entender se havia padrões ocultos entre os passageiros que possam explicar esse desfecho.</p>
<p>A base de dados Space Titanic, inspirada no clássico Titanic e disponível no <a href="https://www.kaggle.com"><code>Kaggle</code></a>, será utilizada para trabalharmos técnicas de clusterização não supervisionada, que nos permitem:</p>
<ul>
<li><p>🔍 Descobrir grupos de passageiros com perfis semelhantes;</p></li>
<li><p>🧠 Analisar comportamentos e características emergentes em cada grupo;</p></li>
<li><p>📊 Auxiliar em decisões estratégicas para personalização de serviços, segurança de bordo e planejamento de missões futuras.</p></li>
</ul>
<section id="pacotes-utilizados" class="level2">
<h2 class="anchored" data-anchor-id="pacotes-utilizados">Pacotes utilizados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>load <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  new.pkg <span class="ot">&lt;-</span> pkg[<span class="sc">!</span>(pkg <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(new.pkg))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">install.packages</span>(new.pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sapply</span>(pkg, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Pacotes utilizados nessa análise</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>packages <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"tidyverse"</span>,<span class="st">'tidymodels'</span>, <span class="st">'tidyclust'</span>, <span class="st">'dbscan'</span>, <span class="st">'meanShiftR'</span>, <span class="st">'kohonen'</span>, <span class="st">'doParallel'</span>, <span class="st">'tictoc'</span>, <span class="st">'tidyr'</span>, <span class="st">'purrr'</span>, <span class="st">'cluster'</span>, <span class="st">'umap'</span>, <span class="st">'funModeling'</span>, <span class="st">'clue'</span>, <span class="st">'janitor'</span>, <span class="st">'mclust'</span>, <span class="st">'tictoc'</span>, <span class="st">'future'</span>, <span class="st">'doFuture'</span>, <span class="st">'progressr'</span>, <span class="st">'FactoMineR'</span>, <span class="st">'factoextra'</span>, <span class="st">'vegan'</span>, <span class="st">'clusterCrit'</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(packages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tidyverse  tidymodels   tidyclust      dbscan  meanShiftR     kohonen 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
 doParallel      tictoc       tidyr       purrr     cluster        umap 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
funModeling        clue     janitor      mclust      tictoc      future 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
   doFuture   progressr  FactoMineR  factoextra       vegan clusterCrit 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE </code></pre>
</div>
</div>
</section>
<section id="leitura-dos-dados" class="level2">
<h2 class="anchored" data-anchor-id="leitura-dos-dados">Leitura dos dados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">=</span> rio<span class="sc">::</span><span class="fu">import</span>(<span class="st">"https://raw.githubusercontent.com/tiagomartin/est125/refs/heads/main/dados/space_titanic.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 8,693
Columns: 14
$ PassengerId  &lt;chr&gt; "0001_01", "0002_01", "0003_01", "0003_02", "0004_01", "0…
$ HomePlanet   &lt;chr&gt; "Europa", "Earth", "Europa", "Europa", "Earth", "Earth", …
$ CryoSleep    &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FA…
$ Cabin        &lt;chr&gt; "B/0/P", "F/0/S", "A/0/S", "A/0/S", "F/1/S", "F/0/P", "F/…
$ Destination  &lt;chr&gt; "TRAPPIST-1e", "TRAPPIST-1e", "TRAPPIST-1e", "TRAPPIST-1e…
$ Age          &lt;dbl&gt; 39, 24, 58, 33, 16, 44, 26, 28, 35, 14, 34, 45, 32, 48, 2…
$ VIP          &lt;lgl&gt; FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FA…
$ RoomService  &lt;dbl&gt; 0, 109, 43, 0, 303, 0, 42, 0, 0, 0, 0, 39, 73, 719, 8, 32…
$ FoodCourt    &lt;dbl&gt; 0, 9, 3576, 1283, 70, 483, 1539, 0, 785, 0, 0, 7295, 0, 1…
$ ShoppingMall &lt;dbl&gt; 0, 25, 0, 371, 151, 0, 3, 0, 17, 0, NA, 589, 1123, 65, 12…
$ Spa          &lt;dbl&gt; 0, 549, 6715, 3329, 565, 291, 0, 0, 216, 0, 0, 110, 0, 0,…
$ VRDeck       &lt;dbl&gt; 0, 44, 49, 193, 2, 0, 0, NA, 0, 0, 0, 124, 113, 24, 7, 0,…
$ Name         &lt;chr&gt; "Maham Ofracculy", "Juanna Vines", "Altark Susent", "Sola…
$ Transported  &lt;lgl&gt; FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">%&gt;%</span> <span class="fu">df_status</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       variable q_zeros p_zeros q_na p_na q_inf p_inf      type unique
1   PassengerId       0    0.00    0 0.00     0     0 character   8693
2    HomePlanet       0    0.00    0 0.00     0     0 character      4
3     CryoSleep    5439   62.57  217 2.50     0     0   logical      2
4         Cabin       0    0.00    0 0.00     0     0 character   6561
5   Destination       0    0.00    0 0.00     0     0 character      4
6           Age     178    2.05  179 2.06     0     0   numeric     80
7           VIP    8291   95.38  203 2.34     0     0   logical      2
8   RoomService    5577   64.16  181 2.08     0     0   numeric   1273
9     FoodCourt    5456   62.76  183 2.11     0     0   numeric   1507
10 ShoppingMall    5587   64.27  208 2.39     0     0   numeric   1115
11          Spa    5324   61.24  183 2.11     0     0   numeric   1327
12       VRDeck    5495   63.21  188 2.16     0     0   numeric   1306
13         Name       0    0.00    0 0.00     0     0 character   8474
14  Transported    4315   49.64    0 0.00     0     0   logical      2</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)  <span class="co"># Escolha um número fixo qualquer</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>De análises anteriores, propomos as seguintes novas variáveis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Engenharia de variáveis</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">=</span> dados <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(Cabin, <span class="fu">c</span>(<span class="st">"CabinDeck"</span>, <span class="st">"CabinNum"</span>, <span class="st">"CabinSide"</span>), <span class="at">sep =</span> <span class="st">"/"</span>, <span class="at">remove =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(PassengerId, <span class="fu">c</span>(<span class="st">"PassGroup"</span>, <span class="st">"nGroup"</span>), <span class="at">sep =</span> <span class="st">"_"</span>, <span class="at">remove =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CabinDeck =</span> <span class="fu">as.factor</span>(CabinDeck),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">CabinSide =</span> <span class="fu">as.factor</span>(CabinSide), </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">PassGroup =</span> <span class="fu">as.numeric</span>(PassGroup))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="receita-de-pré-processamento" class="level2">
<h2 class="anchored" data-anchor-id="receita-de-pré-processamento">Receita de pré-processamento</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>receita <span class="ot">=</span> <span class="fu">recipe</span>(<span class="sc">~</span> ., <span class="at">data =</span> dados) <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(Name, Transported) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), as.factor)) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">GroupSize =</span> <span class="fu">as.integer</span>(purrr<span class="sc">::</span><span class="fu">map_dbl</span>(PassGroup, <span class="sc">~</span> <span class="fu">sum</span>(PassGroup <span class="sc">==</span> .x))),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">IsAlone =</span> <span class="fu">ifelse</span>(GroupSize<span class="sc">==</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">as.factor</span>(),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">CabinNum =</span> <span class="fu">as.numeric</span>(CabinNum),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">nGroup =</span> <span class="fu">as.numeric</span>(nGroup),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">VIP =</span> <span class="fu">as.factor</span>(VIP),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">CryoSleep =</span> <span class="fu">ifelse</span>((RoomService <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">|</span> FoodCourt <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">|</span> ShoppingMall <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">|</span> Spa <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">|</span> VRDeck <span class="sc">&gt;</span> <span class="dv">0</span>), tidyr<span class="sc">::</span><span class="fu">replace_na</span>(CryoSleep, <span class="cn">FALSE</span>),<span class="cn">TRUE</span>),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">CryoSleep =</span> <span class="fu">as.factor</span>(CryoSleep)) <span class="sc">%&gt;%</span> </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_knn</span>(CryoSleep, <span class="at">neighbors =</span> <span class="dv">2</span>, <span class="at">impute_with =</span> <span class="fu">imp_vars</span>(PassGroup, CabinDeck, CabinNum, CabinSide)) <span class="sc">%&gt;%</span> </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">RoomService =</span> <span class="fu">ifelse</span>(CryoSleep<span class="sc">==</span><span class="cn">TRUE</span>, tidyr<span class="sc">::</span><span class="fu">replace_na</span>(RoomService, <span class="dv">0</span>),RoomService),</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">FoodCourt =</span> <span class="fu">ifelse</span>(CryoSleep<span class="sc">==</span><span class="cn">TRUE</span>, tidyr<span class="sc">::</span><span class="fu">replace_na</span>(FoodCourt, <span class="dv">0</span>),FoodCourt),</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">ShoppingMall =</span> <span class="fu">ifelse</span>(CryoSleep<span class="sc">==</span><span class="cn">TRUE</span>, tidyr<span class="sc">::</span><span class="fu">replace_na</span>(ShoppingMall, <span class="dv">0</span>), ShoppingMall),</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Spa =</span> <span class="fu">ifelse</span>(CryoSleep<span class="sc">==</span><span class="cn">TRUE</span>, tidyr<span class="sc">::</span><span class="fu">replace_na</span>(Spa, <span class="dv">0</span>), Spa),</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">VRDeck =</span> <span class="fu">ifelse</span>(CryoSleep<span class="sc">==</span><span class="cn">TRUE</span>, tidyr<span class="sc">::</span><span class="fu">replace_na</span>(VRDeck, <span class="dv">0</span>), VRDeck)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_knn</span>(RoomService, FoodCourt, ShoppingMall, Spa, VRDeck, <span class="at">neighbors =</span> <span class="dv">2</span>, </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>                  <span class="at">impute_with =</span> <span class="fu">imp_vars</span>(PassGroup, CabinDeck, CabinNum, CabinSide)) <span class="sc">%&gt;%</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_bag</span>(Age, VIP, CryoSleep, Destination, HomePlanet, CabinDeck, CabinNum, </span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>                  CabinSide) <span class="sc">%&gt;%</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(<span class="fu">across</span>(RoomService<span class="sc">:</span>VRDeck, <span class="sc">~</span> <span class="fu">log10</span>(. <span class="sc">+</span> <span class="dv">1</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(<span class="at">despesasSuperfluas =</span> RoomService <span class="sc">+</span> Spa <span class="sc">+</span> VRDeck,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>              <span class="at">despesasBasicas =</span> FoodCourt <span class="sc">+</span> ShoppingMall,</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>              <span class="at">Isearth =</span> <span class="fu">ifelse</span>(HomePlanet<span class="sc">==</span><span class="st">'Earth'</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">as.factor</span>(),</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>              <span class="at">Iskid =</span> <span class="fu">ifelse</span>(Age <span class="sc">&lt;</span> <span class="dv">14</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="fu">as.factor</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(PassGroup) <span class="sc">%&gt;%</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_corr</span>(<span class="fu">all_numeric_predictors</span>(), <span class="at">threshold =</span> <span class="fl">0.95</span>) <span class="sc">%&gt;%</span>  <span class="co"># Remove colineares</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_nzv</span>(<span class="fu">all_predictors</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pré-processamento-fora-do-tuning" class="level2">
<h2 class="anchored" data-anchor-id="pré-processamento-fora-do-tuning">Pré-processamento fora do tuning</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>prep_dados <span class="ot">&lt;-</span> <span class="fu">prep</span>(receita)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dados_prep <span class="ot">&lt;-</span> <span class="fu">bake</span>(prep_dados, <span class="at">new_data =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dados_prep <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 8,693
Columns: 28
$ nGroup                    &lt;dbl&gt; -0.4911332, -0.4911332, -0.4911332, 0.457416…
$ CabinNum                  &lt;dbl&gt; -1.88552650, -1.88552650, -1.88552650, -1.88…
$ Age                       &lt;dbl&gt; 0.70841598, -0.33569386, 2.03095510, 0.29077…
$ RoomService               &lt;dbl&gt; -0.6523874, 1.0620923, 0.7278793, -0.6523874…
$ FoodCourt                 &lt;dbl&gt; -0.6640943, 0.1155437, 2.1063642, 1.7594612,…
$ ShoppingMall              &lt;dbl&gt; -0.63553377, 0.62593994, -0.63553377, 1.6561…
$ Spa                       &lt;dbl&gt; -0.6780625, 1.5859232, 2.4837539, 2.2320499,…
$ VRDeck                    &lt;dbl&gt; -0.65344522, 0.72259213, 0.76067799, 1.25078…
$ GroupSize                 &lt;dbl&gt; -0.6486974, -0.6486974, -0.0222670, -0.02226…
$ despesasSuperfluas        &lt;dbl&gt; -0.96031582, 1.63333401, 1.92940474, 1.38153…
$ despesasBasicas           &lt;dbl&gt; -0.8759684, 0.4760396, 1.1134474, 2.3034453,…
$ HomePlanet_Earth          &lt;dbl&gt; -1.0605560, 0.9427932, -1.0605560, -1.060556…
$ HomePlanet_Europa         &lt;dbl&gt; 1.7546941, -0.5698344, 1.7546941, 1.7546941,…
$ HomePlanet_Mars           &lt;dbl&gt; -0.5036351, -0.5036351, -0.5036351, -0.50363…
$ CryoSleep_TRUE.           &lt;dbl&gt; 1.228852, -0.813674, -0.813674, -0.813674, -…
$ CabinDeck_B               &lt;dbl&gt; 3.1871633, -0.3137225, -0.3137225, -0.313722…
$ CabinDeck_C               &lt;dbl&gt; -0.3065922, -0.3065922, -0.3065922, -0.30659…
$ CabinDeck_D               &lt;dbl&gt; -0.2412044, -0.2412044, -0.2412044, -0.24120…
$ CabinDeck_E               &lt;dbl&gt; -0.3347395, -0.3347395, -0.3347395, -0.33473…
$ CabinDeck_F               &lt;dbl&gt; -0.6881752, 1.4529512, -0.6881752, -0.688175…
$ CabinDeck_G               &lt;dbl&gt; -0.6458598, -0.6458598, -0.6458598, -0.64585…
$ CabinSide_S               &lt;dbl&gt; -1.0113959, 0.9886188, 0.9886188, 0.9886188,…
$ Destination_X55.Cancri.e  &lt;dbl&gt; -0.5109838, -0.5109838, -0.5109838, -0.51098…
$ Destination_PSO.J318.5.22 &lt;dbl&gt; -0.3174684, -0.3174684, -0.3174684, -0.31746…
$ Destination_TRAPPIST.1e   &lt;dbl&gt; 0.6852732, 0.6852732, 0.6852732, 0.6852732, …
$ IsAlone_X1                &lt;dbl&gt; 0.8994799, 0.8994799, -1.1116257, -1.1116257…
$ Isearth_X1                &lt;dbl&gt; -1.0605560, 0.9427932, -1.0605560, -1.060556…
$ Iskid_X1                  &lt;dbl&gt; -0.353350, -0.353350, -0.353350, -0.353350, …</code></pre>
</div>
</div>
</section>
<section id="verificando-a-estrutura-de-agrupamento-com-pca" class="level2">
<h2 class="anchored" data-anchor-id="verificando-a-estrutura-de-agrupamento-com-pca">Verificando a Estrutura de Agrupamento com PCA</h2>
<p>Antes de aplicar algoritmos de clusterização, é essencial compreender a estrutura de correlação intrínseca dos dados, ou seja, se os dados realmente apresentam indícios de agrupamentos naturais. Uma das formas mais eficazes e intuitivas de verificar isso é por meio de uma análise exploratória baseada em Análise de Componentes Principais (PCA).</p>
<p>A PCA reduz a dimensionalidade dos dados ao projetá-los em um novo sistema de eixos ortogonais (as componentes principais) que maximizam a variância explicada. Ao analisar os dados projetados nas duas primeiras componentes principais, é possível visualizar possíveis agrupamentos naturais, outliers e sobreposições.</p>
<p>Essa visualização também permite:</p>
<ul>
<li><p>Avaliar a separabilidade dos grupos esperados;</p></li>
<li><p>Identificar variáveis que mais contribuem para a estrutura dos dados;</p></li>
<li><p>Decidir se faz sentido aplicar técnicas de clusterização.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pca_result <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(dados_prep, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(pca_result, <span class="at">col.ind =</span> <span class="st">"grey70"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="definição-dos-modelos-k-means-e-hierárquico" class="level2">
<h2 class="anchored" data-anchor-id="definição-dos-modelos-k-means-e-hierárquico">Definição dos modelos K-means e Hierárquico</h2>
<p>Antes de ajustarmos os modelos de clusterização, é necessário definir suas configurações por meio dos <em>model specifications</em> no framework <code>tidymodels</code>, utilizando o pacote <code>tidyclust</code>. Essa etapa permite estabelecer os principais parâmetros do modelo, como o número de grupos a ser ajustado (<code>tune()</code>), o mecanismo de execução (<code>engine</code>) e o modo de operação (<code>partition</code> para métodos de agrupamento).</p>
<p>Atualmente, o pacote <code>tidyclust</code> oferece suporte apenas a dois algoritmos de clusterização: <strong>K-means</strong> e <strong>Clusterização Hierárquica Aglomerativa</strong>. A seguir, criamos as especificações para esses dois métodos:</p>
<ul>
<li><p><code>kmeans_spec</code>: define o modelo K-means, que busca particionar os dados em grupos minimizando a variabilidade interna de cada cluster.</p></li>
<li><p><code>hclust_spec</code>: define o modelo hierárquico, com ligação do tipo <code>ward.D</code>, que constrói agrupamentos de forma incremental buscando minimizar o aumento da variância total entre grupos.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>kmeans_spec <span class="ot">&lt;-</span> <span class="fu">k_means</span>(<span class="at">num_clusters =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"stats"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"partition"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>hclust_spec <span class="ot">&lt;-</span> <span class="fu">hier_clust</span>(<span class="at">num_clusters =</span> <span class="fu">tune</span>(), <span class="at">linkage_method =</span> <span class="st">"ward.D2"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"stats"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"partition"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ambas as especificações usam o motor <code>stats</code>, que corresponde às implementações nativas do R. Essas definições servirão como base para a construção dos <em>workflows</em> de clusterização, permitindo a validação cruzada e o ajuste automático do número ideal de grupos com base nos dados analisados.</p>
</section>
<section id="tuning-com-validação-cruzada" class="level2">
<h2 class="anchored" data-anchor-id="tuning-com-validação-cruzada">Tuning com validação cruzada</h2>
<p>Com as especificações dos modelos definidas, o próximo passo consiste na construção dos <em>workflows</em> e na execução do processo de ajuste dos hiperparâmetros, neste caso, o número de clusters.</p>
<p>Primeiramente, utilizamos a função <code>vfold_cv()</code> para gerar um esquema de validação cruzada com 5 partições, garantindo uma avaliação robusta da performance dos modelos em diferentes subconjuntos dos dados (<code>dados_prep</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>folds_prep <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(dados_prep, <span class="at">v =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Em seguida, criamos dois <em>workflows</em>, um para o modelo K-means e outro para o modelo Hierárquico. Ambos são configurados para usar todos os preditores disponíveis na base de dados <code>(~ .)</code> e incorporam suas respectivas especificações (<code>kmeans_spec</code> e <code>hclust_spec</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>wf_kmeans <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(kmeans_spec) <span class="sc">%&gt;%</span> <span class="fu">add_formula</span>(<span class="sc">~</span> .)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>wf_hclust <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(hclust_spec) <span class="sc">%&gt;%</span> <span class="fu">add_formula</span>(<span class="sc">~</span> .)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O grid de valores para o hiperparâmetro <code>num_clusters</code> é definido entre 2 e 10, permitindo que o processo de tuning explore diferentes possíveis quantidades de agrupamentos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">num_clusters =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Por fim, aplicamos a função <code>tune_cluster()</code> para cada modelo, realizando o ajuste do número de clusters com base na métrica de avaliação silhueta média (<code>silhouette_avg</code>), uma medida amplamente utilizada para quantificar a qualidade dos agrupamentos formados. Essa métrica avalia o quão bem cada ponto está agrupado com seus vizinhos em comparação com outros clusters.</p>
<p>Esse processo nos permitirá comparar o desempenho dos modelos e selecionar o número ideal de grupos de forma sistemática e fundamentada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Plano com paralelismo</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plan</span>(multisession, <span class="at">workers =</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoFuture</span>()</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">handlers</span>(<span class="st">"txtprogressbar"</span>)  <span class="co"># ou "progress"</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">with_progress</span>({</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>res_kmeans <span class="ot">&lt;-</span> <span class="fu">tune_cluster</span>(</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  wf_kmeans,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> folds_prep,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> grid,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">cluster_metric_set</span>(silhouette_avg)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="fu">with_progress</span>({</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>res_hclust <span class="ot">&lt;-</span> <span class="fu">tune_cluster</span>(</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  wf_hclust,</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> folds_prep,</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> grid,</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">cluster_metric_set</span>(silhouette_avg)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1775.67 sec elapsed</code></pre>
</div>
</div>
</section>
<section id="resultados-e-melhor-modelo" class="level2">
<h2 class="anchored" data-anchor-id="resultados-e-melhor-modelo">Resultados e melhor modelo</h2>
<p>Após a execução do processo de tuning com validação cruzada, o próximo passo é identificar o número ideal de clusters para cada modelo com base na métrica de avaliação escolhida, neste caso, a silhueta média (<code>silhouette_avg</code>). Essa métrica indica quão bem as observações estão agrupadas: valores próximos de 1 sugerem melhor separação entre os grupos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>melhor_kmeans <span class="ot">&lt;-</span> <span class="fu">select_best</span>(res_kmeans, <span class="at">metric =</span> <span class="st">"silhouette_avg"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>melhor_hclust <span class="ot">&lt;-</span> <span class="fu">select_best</span>(res_hclust, <span class="at">metric =</span> <span class="st">"silhouette_avg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Utilizamos a função <code>select_best()</code> para extrair, de forma automática, o valor de <code>num_clusters</code> que resultou na melhor performance para cada modelo. Em seguida, atualizamos as especificações dos modelos K-means e Hierárquico com o número de clusters ótimo encontrado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>kmeans_final <span class="ot">&lt;-</span> <span class="fu">k_means</span>(<span class="at">num_clusters =</span> melhor_kmeans<span class="sc">$</span>num_clusters) <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"stats"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"partition"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>hclust_final <span class="ot">&lt;-</span> <span class="fu">hier_clust</span>(<span class="at">num_clusters =</span> melhor_hclust<span class="sc">$</span>num_clusters, <span class="at">linkage_method =</span> <span class="st">"ward.D"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"stats"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"partition"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Com os modelos atualizados, recriamos os <em>workflows</em> finais utilizando a função <code>update_model()</code>, garantindo que cada <em>workflow</em> reflita o melhor número de grupos encontrado durante o tuning.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>workflow_final_kmeans <span class="ot">&lt;-</span> wf_kmeans <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">update_model</span>(kmeans_final)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>workflow_final_hclust <span class="ot">&lt;-</span> wf_hclust <span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">update_model</span>(hclust_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Por fim, ajustamos os modelos finais aos dados completos (<code>dados_prep</code>) utilizando a função <code>fit()</code>. As predições geradas (<code>predict()</code>) nos fornecem os rótulos de cluster para cada observação, permitindo identificar a qual grupo cada indivíduo foi atribuído. Esses rótulos são armazenados nas variáveis <code>grupos_kmeans</code> e <code>grupos_hierarquico</code>, que serão posteriormente utilizados para interpretação e visualização dos padrões encontrados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>modelo_final_kmeans <span class="ot">&lt;-</span> <span class="fu">fit</span>(workflow_final_kmeans, <span class="at">data =</span> dados_prep)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>grupos_kmeans <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">predict</span>(modelo_final_kmeans, <span class="at">new_data =</span> dados_prep)<span class="sc">$</span>.pred_cluster)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>modelo_final_hclust <span class="ot">&lt;-</span> <span class="fu">fit</span>(workflow_final_hclust, <span class="at">data =</span> dados_prep)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>grupos_hierarquico <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">predict</span>(modelo_final_hclust, <span class="at">new_data =</span> dados_prep)<span class="sc">$</span>.pred_cluster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Esse processo assegura que os modelos finais utilizados para análise estejam otimizados em relação à estrutura dos dados e fundamentados em uma métrica de qualidade apropriada para tarefas de clusterização.</p>
</section>
<section id="visualização-de-grupos-gerados-via-pca" class="level2">
<h2 class="anchored" data-anchor-id="visualização-de-grupos-gerados-via-pca">Visualização de Grupos Gerados via PCA</h2>
<p>Em tarefas de clusterização, é comum gerar agrupamentos com base em medidas de similaridade ou distância entre observações. No entanto, como os dados frequentemente têm muitas variáveis (ou dimensões), torna-se desafiador visualizar e interpretar os agrupamentos diretamente no espaço original.</p>
<p>Para lidar com esse problema, uma técnica amplamente utilizada é a Análise de Componentes Principais (<code>PCA</code>). A <code>PCA</code> transforma os dados originais em um novo sistema de coordenadas formado por componentes principais, isto é, combinações lineares das variáveis originais que maximizam a variância explicada. As duas primeiras componentes geralmente capturam a maior parte da estrutura dos dados, possibilitando uma visualização bidimensional informativa.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  pca_result,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom.ind =</span> <span class="st">"point"</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.ind =</span> grupos_kmeans,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="st">"Set2"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">addEllipses =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title =</span> <span class="st">"Grupo"</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Visualização dos Grupos Formados no Espaço das Componentes Principais"</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  pca_result,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom.ind =</span> <span class="st">"point"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.ind =</span> grupos_hierarquico,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="st">"Set2"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">addEllipses =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title =</span> <span class="st">"Grupo"</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Visualização dos Grupos Formados no Espaço das Componentes Principais"</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao projetar os dados nesse plano PCA e colorir os pontos de acordo com os grupos gerados por um algoritmo de clusterização, conseguimos:</p>
<ul>
<li><p>Visualizar a separação (ou sobreposição) entre os grupos;</p></li>
<li><p>Avaliar a qualidade da segmentação de forma intuitiva;</p></li>
<li><p>Identificar outliers ou observações ambíguas;</p></li>
<li><p>Validar visualmente se há coerência entre os agrupamentos e a estrutura intrínseca dos dados.</p></li>
</ul>
<p>Além disso, o uso de elipses de confiança pode reforçar a noção de centralidade e dispersão de cada grupo, tornando a visualização ainda mais interpretável.</p>
</section>
<section id="tuning-manual-de-dbscan-meanshift-e-som" class="level2">
<h2 class="anchored" data-anchor-id="tuning-manual-de-dbscan-meanshift-e-som">Tuning manual de DBSCAN, MeanShift e SOM</h2>
<p>Diferentemente dos métodos K-means e Hierarchical Clustering, que podem ser facilmente integrados ao framework <code>tidyclust</code> e ajustados automaticamente via validação cruzada com <code>tune_cluster()</code>, os algoritmos DBSCAN, MeanShift e Redes SOM exigem uma abordagem manual de tuning dos hiperparâmetros. Isso se deve a características específicas desses modelos e às limitações atuais das interfaces automatizadas.</p>
<section id="tuning-de-dbscan" class="level3">
<h3 class="anchored" data-anchor-id="tuning-de-dbscan">Tuning de DBSCAN</h3>
<p>Como o algoritmo DBSCAN não possui uma etapa automática de ajuste de hiperparâmetros integrada ao <code>tidyclust</code>, é necessário realizar o tuning manual dos dois parâmetros fundamentais do modelo:</p>
<ul>
<li><p><code>eps</code>: raio de vizinhança que define a densidade mínima em torno de um ponto;</p></li>
<li><p><code>minPts</code>: número mínimo de pontos necessário para formar uma região densa (núcleo do cluster).</p></li>
</ul>
<p>Para facilitar esse processo, definimos a função <code>avaliar_dbscan()</code>, que recebe diferentes combinações de <code>eps</code> e <code>minPts</code> e avalia o desempenho do modelo com base na média do índice de silhueta, uma métrica que quantifica o quão bem cada observação está agrupada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>avaliar_dbscan <span class="ot">&lt;-</span> <span class="cf">function</span>(eps, minPts, dados) {</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  modelo <span class="ot">&lt;-</span> dbscan<span class="sc">::</span><span class="fu">dbscan</span>(dados, <span class="at">eps =</span> eps, <span class="at">minPts =</span> minPts)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove ruído (cluster 0)</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  grupos <span class="ot">&lt;-</span> modelo<span class="sc">$</span>cluster</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  grupos_validos <span class="ot">&lt;-</span> grupos[grupos <span class="sc">!=</span> <span class="dv">0</span>]</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  n_clusters <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(grupos_validos))</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcular a silhueta apenas se houver pelo menos dois grupos distintos (além de ruído)</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (n_clusters <span class="sc">&gt;</span> <span class="dv">1</span>) {</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    sil <span class="ot">&lt;-</span> <span class="fu">silhouette</span>(grupos, <span class="fu">dist</span>(dados))</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    media_sil <span class="ot">&lt;-</span> <span class="fu">mean</span>(sil[, <span class="dv">3</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    media_sil <span class="ot">&lt;-</span> <span class="cn">NA_real_</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">eps =</span> eps,</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">minPts =</span> minPts,</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_clusters =</span> n_clusters,</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">silhueta =</span> media_sil</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Essa abordagem permite montar uma <code>grid</code> de busca com diferentes valores de <code>eps</code> e <code>minPts</code>, testando várias combinações para selecionar aquela que maximiza a separação entre os clusters e minimiza a presença de ruído.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grid de hiperparâmetros</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>eps_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">3.0</span>, <span class="fl">4.0</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>minPts_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">10</span>, <span class="dv">30</span>, <span class="at">by =</span> <span class="dv">2</span>)   <span class="co"># Mínimo de pontos mais restritivo</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Seguindo, construimos um grid de parâmetros por meio da função <code>expand.grid()</code>, combinando todos os valores possíveis de <code>eps</code> e <code>minPts</code> definidos previamente nas variáveis <code>eps_grid</code> e <code>minPts_grid</code>. Utilizamos a função <code>pmap_dfr()</code> (do pacote <code>purrr</code>) para aplicar a função <code>avaliar_dbscan()</code> a cada combinação da grid. O argumento <code>.progress =</code> permite o acompanhamento da execução, útil especialmente em grades extensas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>dbscan_results <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">eps =</span> eps_grid, <span class="at">minPts =</span> minPts_grid) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">silhouette =</span> <span class="fu">pmap_dfr</span>(<span class="fu">list</span>(eps, minPts), avaliar_dbscan, <span class="at">dados =</span> dados_prep, <span class="at">.progress =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(silhouette<span class="sc">$</span>silhueta))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>373.43 sec elapsed</code></pre>
</div>
</div>
<p>Os resultados são ordenados em ordem decrescente de acordo com a silhueta média, permitindo identificar rapidamente os conjuntos de parâmetros que produziram os melhores agrupamentos em termos de coesão e separação dos grupos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>melhor_dbscan <span class="ot">&lt;-</span> dbscan_results <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(silhouette<span class="sc">$</span>silhueta), silhouette<span class="sc">$</span>n_clusters <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(silhouette<span class="sc">$</span>silhueta)) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(silhouette)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Com os valores ideais de <code>eps</code> e <code>minPts</code> em mãos, ajustamos o modelo DBSCAN final sobre os dados completos (<code>dados_prep</code>). Os rótulos de cluster atribuídos pelo modelo são armazenados em <code>grupos_dbscan</code>, e podem assumir os valores 1, 2, 3 para os grupos válidos e 0 para os pontos classificados como ruído.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>modelo_dbscan <span class="ot">&lt;-</span> <span class="fu">dbscan</span>(dados_prep, <span class="at">eps =</span> melhor_dbscan<span class="sc">$</span>eps, <span class="at">minPts =</span> melhor_dbscan<span class="sc">$</span>minPts)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>grupos_dbscan <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(modelo_dbscan<span class="sc">$</span>cluster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para facilitar a interpretação visual dos agrupamentos encontrados, utilizamos novamente a projeção PCA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  pca_result,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom.ind =</span> <span class="st">"point"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.ind =</span> grupos_dbscan,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="st">"Set2"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">addEllipses =</span> <span class="cn">TRUE</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title =</span> <span class="st">"Grupo"</span>,</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Visualização dos Grupos Formados no Espaço das Componentes Principais"</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tuning-de-meanshift" class="level3">
<h3 class="anchored" data-anchor-id="tuning-de-meanshift">Tuning de MeanShift</h3>
<p>O algoritmo <strong>MeanShift</strong> é um método de clusterização baseado em densidade que não exige a definição prévia do número de clusters. No entanto, seu desempenho é altamente sensível à escolha do parâmetro <code>bandwidth</code>, que determina o raio de influência ao redor de cada ponto para estimar os modos da distribuição dos dados.</p>
<p>Como o <code>tidyclust</code> ainda não oferece suporte nativo ao MeanShift, a definição do melhor modelo deve ser feita manual e empiricamente, avaliando diferentes valores de <code>bandwidth</code>.</p>
<p>Para isso, implementamos duas funções: A função <code>avaliar_meanshift()</code>, que aplica o algoritmo <code>meanShiftR::meanShift()</code> a uma matriz de dados com um vetor de <code>bandwidth</code> (um valor para cada variável)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>avaliar_meanshift <span class="ot">&lt;-</span> <span class="cf">function</span>(bandwidth, dados) {</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aplica o MeanShift com o vetor de bandwidth</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  modelo <span class="ot">&lt;-</span> meanShiftR<span class="sc">::</span><span class="fu">meanShift</span>(dados, <span class="at">bandwidth =</span> bandwidth)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Grupos</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  grupos <span class="ot">&lt;-</span> modelo<span class="sc">$</span>assignment <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Verifica se há mais de um grupo</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(<span class="fu">unique</span>(grupos)) <span class="sc">&lt;</span> <span class="dv">2</span>) {</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">tibble</span>(</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">bandwidth =</span> <span class="fu">list</span>(bandwidth),</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">silhueta =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">n_clusters =</span> <span class="dv">1</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcula silhueta</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>  sil <span class="ot">&lt;-</span> <span class="fu">silhouette</span>(grupos, <span class="fu">dist</span>(dados))</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>  sil_media <span class="ot">&lt;-</span> <span class="fu">mean</span>(sil[, <span class="dv">3</span>])</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Retorna tibble</span></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">bandwidth =</span> <span class="fu">list</span>(bandwidth),</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">silhueta =</span> sil_media,</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_clusters =</span> <span class="fu">length</span>(<span class="fu">unique</span>(grupos))</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>E a função <code>tuning_meanshift()</code>, que gera uma grid de vetores de <code>bandwidth</code> multiplicando o desvio padrão de cada variável por uma sequência de fatores escalares (de 1.5 a 5.0). Para cada vetor de <code>bandwidth</code>, aplicamos a função <code>avaliar_meanshift()</code> e armazenamos os resultados, possibilitando identificar a combinação que resulta na melhor estrutura de agrupamento com base na silhueta média.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>tuning_meanshift <span class="ot">&lt;-</span> <span class="cf">function</span>(dados) {</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Grid de escalas maiores para reduzir o número de grupos</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  sd_vars <span class="ot">&lt;-</span> <span class="fu">apply</span>(dados, <span class="dv">2</span>, sd)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  escalas <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">1.5</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  bw_grid <span class="ot">&lt;-</span> <span class="fu">lapply</span>(escalas, <span class="cf">function</span>(e) e <span class="sc">*</span> sd_vars)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Avalia cada vetor de bandwidth</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  resultados <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map_dfr</span>(bw_grid, <span class="sc">~</span><span class="fu">avaliar_meanshift</span>(.x, dados))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(resultados)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O objeto final <code>resultado</code> contém todas as combinações testadas e suas respectivas performances, servindo de base para a escolha do <code>bandwidth</code> ideal para o modelo MeanShift.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>resultado <span class="ot">&lt;-</span> <span class="fu">tuning_meanshift</span>(<span class="fu">as.matrix</span>(dados_prep))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2781.31 sec elapsed</code></pre>
</div>
</div>
<p>Após testarmos diversas combinações de <code>bandwidth</code> utilizando a função <code>tuning_meanshift()</code>, o próximo passo consiste em selecionar a melhor configuração para o modelo MeanShift com base na silhueta média.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>melhor_bw <span class="ot">&lt;-</span> resultado <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(silhueta), n_clusters <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(silhueta)) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(bandwidth) <span class="sc">%&gt;%</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  .[[<span class="dv">1</span>]]</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>modelo_meanshift <span class="ot">&lt;-</span> <span class="fu">meanShift</span>(<span class="fu">as.matrix</span>(dados_prep), <span class="at">bandwidth =</span> melhor_bw)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>grupos_meanshift <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(modelo_meanshift<span class="sc">$</span>assignment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Os rótulos de cluster obtidos pelo modelo são então utilizados para construir uma visualização bidimensional via PCA, facilitando a interpretação visual dos agrupamentos. No gráfico gerado, cada ponto representa uma observação, posicionada de acordo com os escores das componentes e colorida segundo o cluster ao qual pertence.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  pca_result,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom.ind =</span> <span class="st">"point"</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.ind =</span> grupos_meanshift,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="st">"Set2"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">addEllipses =</span> <span class="cn">TRUE</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title =</span> <span class="st">"Grupo"</span>,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Visualização dos Grupos Formados no Espaço das Componentes Principais"</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tuning-de-redes-som-kohonen" class="level3">
<h3 class="anchored" data-anchor-id="tuning-de-redes-som-kohonen">Tuning de Redes SOM (Kohonen)</h3>
<p>Diferentemente de métodos clássicos como K-means, as Redes de Kohonen (SOM – Self-Organizing Maps) formam agrupamentos de forma não supervisionada a partir de uma grade de neurônios, cuja estrutura (dimensão, topologia, taxa de aprendizado, número de iterações) impacta diretamente a qualidade dos grupos formados.</p>
<p>Como o pacote <code>tidyclust</code> ainda não oferece suporte direto para SOMs, o processo de tuning dos hiperparâmetros deve ser feito manualmente. Para isso, foi criada a função <code>avaliar_som()</code>, que recebe os principais hiperparâmetros do modelo e avalia sua performance de clusterização por meio do índice de silhueta média.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>avaliar_som <span class="ot">&lt;-</span> <span class="cf">function</span>(xdim, ydim, topo, rlen, alpha, dados) {</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  grid <span class="ot">&lt;-</span> <span class="fu">somgrid</span>(<span class="at">xdim =</span> xdim, <span class="at">ydim =</span> ydim, <span class="at">topo =</span> topo)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  modelo <span class="ot">&lt;-</span> <span class="fu">som</span>(</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">X =</span> dados,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">grid =</span> grid,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">rlen =</span> rlen,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> alpha,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">keep.data =</span> <span class="cn">TRUE</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  grupos <span class="ot">&lt;-</span> modelo<span class="sc">$</span>unit.classif</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(<span class="fu">unique</span>(grupos)) <span class="sc">&lt;</span> <span class="dv">2</span>) {</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">tibble</span>(</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">xdim =</span> xdim,</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">ydim =</span> ydim,</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">topo =</span> topo,</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">rlen =</span> rlen,</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">alpha =</span> <span class="fu">paste</span>(alpha, <span class="at">collapse =</span> <span class="st">"-"</span>),</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">silhueta =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">n_clusters =</span> <span class="fu">length</span>(<span class="fu">unique</span>(grupos))</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>  sil <span class="ot">&lt;-</span> <span class="fu">silhouette</span>(grupos, <span class="fu">dist</span>(dados))</span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>  sil_media <span class="ot">&lt;-</span> <span class="fu">mean</span>(sil[, <span class="dv">3</span>])</span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">xdim =</span> xdim,</span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">ydim =</span> ydim,</span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">topo =</span> topo,</span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">rlen =</span> rlen,</span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fu">paste</span>(alpha, <span class="at">collapse =</span> <span class="st">"-"</span>),</span>
<span id="cb39-35"><a href="#cb39-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">silhueta =</span> sil_media,</span>
<span id="cb39-36"><a href="#cb39-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_clusters =</span> <span class="fu">length</span>(<span class="fu">unique</span>(grupos))</span>
<span id="cb39-37"><a href="#cb39-37" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-38"><a href="#cb39-38" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Antes de iniciar o ajuste de modelos SOM, é necessário definir uma grid de busca com diferentes combinações de hiperparâmetros, permitindo explorar sistematicamente o impacto de cada configuração na qualidade dos agrupamentos formados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>xdim_vals <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>ydim_vals <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>topo_vals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"rectangular"</span>, <span class="st">"hexagonal"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>rlen_vals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">400</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>alpha_vals <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.01</span>), <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.01</span>), <span class="fu">c</span>(<span class="fl">0.15</span>, <span class="fl">0.01</span>), <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.01</span>))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>grid_som <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xdim =</span> xdim_vals,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ydim =</span> ydim_vals,</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">topo =</span> topo_vals,</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">rlen =</span> rlen_vals,</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fu">I</span>(alpha_vals),  <span class="co"># evita descompactar a lista</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span> </span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O código acima constrói o grid utilizando a função <code>expand.grid()</code>, combinando os principais parâmetros que controlam o comportamento da rede SOM:</p>
<ul>
<li><p><code>xdim</code> e <code>ydim</code>: definem as dimensões da grade de neurônios (por exemplo, uma grade 3x3 possui 9 unidades de saída). Grades maiores permitem maior resolução nos agrupamentos, mas podem aumentar a complexidade e o risco de overfitting.</p></li>
<li><p><code>topo</code>: especifica a topologia da grade, podendo ser:</p>
<ul>
<li><code>rectangular</code>: disposição clássica dos neurônios em linhas e colunas.</li>
<li><code>hexagonal</code>: cada neurônio possui mais vizinhos imediatos, o que suaviza a transição entre clusters.</li>
</ul></li>
<li><p><code>rlen</code>: define o número de iterações de treinamento da rede. Quanto maior o valor, maior o tempo de treinamento, mas também a chance de convergência mais estável.</p></li>
<li><p><code>alpha</code>: um vetor com dois valores que especificam a taxa de aprendizado inicial e final. Taxas maiores aceleram o aprendizado no início, mas podem comprometer a estabilidade; taxas menores favorecem ajustes mais precisos no final do treinamento.</p></li>
</ul>
<p>Uma observação importante para o parâmetro <code>alpha</code> é que ele é passada como uma lista (<code>I(alpha_vals)</code>) para garantir que cada vetor <code>c(valor_inicial, valor_final)</code> seja tratado como uma unidade indivisível durante a expansão da grid. Isso evita que o <code>expand.grid()</code> desfaça os pares de taxas de aprendizado.</p>
<p>O objeto <code>grid_som</code> resultante contém todas as possíveis combinações entre os valores de cada hiperparâmetro, e será utilizado para ajustar e avaliar diferentes modelos SOM via a função <code>avaliar_som()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>resultado_som <span class="ot">&lt;-</span> <span class="fu">pmap_dfr</span>(</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  grid_som,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(xdim, ydim, topo, rlen, alpha) {</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">avaliar_som</span>(xdim, ydim, topo, rlen, alpha, <span class="at">dados =</span> <span class="fu">as.matrix</span>(dados_prep))</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1224.41 sec elapsed</code></pre>
</div>
</div>
<p>Após a avaliação das diversas combinações de hiperparâmetros, selecionamos agora a melhor configuração da rede SOM com base nos seguintes critérios:</p>
<ul>
<li><p>Formação de no máximo 5 clusters, evitando segmentações excessivamente fragmentadas.</p></li>
<li><p>Maior silhueta média, indicando uma boa separação e coesão entre os grupos formados.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>melhor_som <span class="ot">&lt;-</span> resultado_som <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n_clusters <span class="sc">&lt;=</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(silhueta)) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Com os parâmetros selecionados, configuramos a grade de neurônios com <code>somgrid()</code>, especificando o número de neurônios (<code>xdim</code> × <code>ydim</code>) e a topologia (<code>topo</code>). Em seguida, o modelo SOM é ajustado com:</p>
<ul>
<li><p>Os dados preparados (<code>dados_prep</code>);</p></li>
<li><p>O número de épocas de treinamento (<code>rlen</code>);</p></li>
<li><p>A taxa de aprendizado inicial e final (<code>alpha</code>), convertida novamente de texto para vetor numérico.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">somgrid</span>(<span class="at">xdim =</span> melhor_som<span class="sc">$</span>xdim, <span class="at">ydim =</span> melhor_som<span class="sc">$</span>ydim, <span class="at">topo =</span> melhor_som<span class="sc">$</span>topo)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>modelo_som <span class="ot">&lt;-</span> kohonen<span class="sc">::</span><span class="fu">som</span>(</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">X =</span> <span class="fu">as.matrix</span>(dados_prep),</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> grid,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">rlen =</span> melhor_som<span class="sc">$</span>rlen,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fu">as.numeric</span>(<span class="fu">strsplit</span>(melhor_som<span class="sc">$</span>alpha, <span class="st">"-"</span>)[[<span class="dv">1</span>]]),</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">keep.data =</span> <span class="cn">TRUE</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A saída <code>modelo_som$unit.classif</code> fornece os neurônios vencedores (clusters) para cada observação, representando os grupos aos quais os dados foram atribuídos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>grupos_som <span class="ot">&lt;-</span> modelo_som<span class="sc">$</span>unit.classif</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para interpretar os resultados, aplicamos uma projeção PCA sobre os dados e colorimos os pontos com base nos grupos atribuídos pela rede SOM.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  pca_result,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom.ind =</span> <span class="st">"point"</span>,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.ind =</span> <span class="fu">factor</span>(grupos_som),</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="st">"Set2"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">addEllipses =</span> <span class="cn">TRUE</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title =</span> <span class="st">"Grupo"</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Visualização dos Grupos Formados no Espaço das Componentes Principais"</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="análise-dos-clusters" class="level2">
<h2 class="anchored" data-anchor-id="análise-dos-clusters">Análise dos Clusters</h2>
<p>Após aplicar diferentes algoritmos de clusterização aos dados (K-means, DBSCAN, MeanShift, SOM e Hierárquico), é importante avaliar o grau de concordância entre os agrupamentos gerados por cada método. Para isso, utilizamos o Índice Rand Ajustado (ARI – Adjusted Rand Index), uma métrica amplamente usada para comparar partições, corrigindo a aleatoriedade esperada por acaso.</p>
<p>Para isso, criamos o objeto <code>lista_grupos</code>, que armazena os vetores de rótulos atribuídos por cada método aos dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>lista_grupos <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">kmeans =</span> grupos_kmeans,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">dbscan =</span> grupos_dbscan,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanshift =</span> grupos_meanshift,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">som =</span> grupos_som,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">hierarquico =</span> grupos_hierarquico</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conta o número de grupos únicos gerados por cada método</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>tabela_num_grupos <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map_int</span>(lista_grupos, <span class="sc">~</span> <span class="fu">n_distinct</span>(.x)) <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">enframe</span>(<span class="at">name =</span> <span class="st">"Metodo"</span>, <span class="at">value =</span> <span class="st">"Numero_de_Grupos"</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibe a tabela</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>tabela_num_grupos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Metodo      Numero_de_Grupos
  &lt;chr&gt;                  &lt;int&gt;
1 kmeans                     3
2 dbscan                     4
3 meanshift                  3
4 som                        4
5 hierarquico                3</code></pre>
</div>
</div>
<p>Utilizando a função <code>combn()</code>, criamos todas as combinações possíveis de dois algoritmos para comparar seus agrupamentos entre si. Para cada par de métodos, aplicamos a função <code>adjustedRandIndex()</code> (do pacote <code>mclust</code>), que retorna um valor entre:</p>
<ul>
<li><p>1: agrupamentos idênticos;</p></li>
<li><p>0: agrupamentos não mais concordantes do que o esperado ao acaso;</p></li>
<li><p>&lt; 0: discordância inferior ao esperado aleatoriamente.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gerar todas as combinações de pares de métodos</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>comparacao_ari <span class="ot">&lt;-</span> <span class="fu">combn</span>(<span class="fu">names</span>(lista_grupos), <span class="dv">2</span>, <span class="at">simplify =</span> <span class="cn">FALSE</span>, <span class="at">FUN =</span> <span class="cf">function</span>(par) {</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  ari_val <span class="ot">&lt;-</span> <span class="fu">adjustedRandIndex</span>(lista_grupos[[par[<span class="dv">1</span>]]], lista_grupos[[par[<span class="dv">2</span>]]])</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">metodo1 =</span> par[<span class="dv">1</span>],</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">metodo2 =</span> par[<span class="dv">2</span>],</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">ARI =</span> ari_val</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>}) <span class="sc">%&gt;%</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>() <span class="sc">%&gt;%</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(ARI))</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar resultados</span></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>comparacao_ari</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   metodo1   metodo2          ARI
   &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;
 1 meanshift som          0.498  
 2 kmeans    som          0.443  
 3 kmeans    meanshift    0.353  
 4 meanshift hierarquico  0.136  
 5 som       hierarquico  0.136  
 6 kmeans    dbscan       0.0376 
 7 kmeans    hierarquico  0.00546
 8 dbscan    som         -0.00256
 9 dbscan    meanshift   -0.0118 
10 dbscan    hierarquico -0.0772 </code></pre>
</div>
</div>
</section>
<section id="validação-estatística-dos-agrupamentos" class="level2">
<h2 class="anchored" data-anchor-id="validação-estatística-dos-agrupamentos">Validação Estatística dos Agrupamentos</h2>
<p>Podemos observar que os algoritmos que aparentemente apresentaram as melhores separações em nossa base de dados foram o K-means e as redes SOM. Embora o K-means seja amplamente conhecido por sua velocidade e facilidade de interpretação, ele assume que os grupos possuem forma aproximadamente esférica e tamanho similar, o que pode limitar sua aplicabilidade em dados com estruturas mais complexas. Por outro lado, o SOM é uma técnica baseada em aprendizado não supervisionado que preserva relações topológicas e permite visualizar agrupamentos de forma intuitiva, sendo particularmente útil em bases com não linearidades ou alta dimensionalidade.</p>
<p>A partir de agora, é fundamental ir além da interpretação visual e realizar uma avaliação estatística formal da validade dos grupos formados.</p>
<p>Nesta etapa, buscamos responder à seguinte pergunta:</p>
<blockquote class="blockquote">
<p>“Os grupos encontrados pelos métodos de clusterização representam subdivisões estatisticamente distintas com base nas variáveis originais dos dados?”</p>
</blockquote>
<p>Para essa finalidade, a PERMANOVA (Permutational Multivariate Analysis of Variance) é uma técnica robusta e amplamente utilizada. A PERMANOVA avalia a existência de heterogeneidade entre grupos com base em uma matriz de distâncias (como distâncias euclidianas ou de Gower), ao invés de depender de pressupostos fortes como normalidade multivariada e homogeneidade das variâncias, como ocorre na MANOVA tradicional. A lógica do teste baseia-se em permutações aleatórias dos rótulos dos grupos, calculando a distribuição empírica da estatística F sob a hipótese nula de que não há diferença entre os grupos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir número de núcleos (ex: todos menos 1)</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>n_cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Registrar o cluster</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> <span class="fu">makeCluster</span>(n_cores)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar se grupos estão no formato adequado</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>grupos_kmeans <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(grupos_kmeans)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular a matriz de distâncias (ou usar diretamente no adonis2)</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>dist_matrix <span class="ot">&lt;-</span> <span class="fu">dist</span>(dados_prep, <span class="at">method =</span> <span class="st">"euclidean"</span>)</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Executar PERMANOVA com paralelização</span></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>resultado_permanova <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> dist_matrix <span class="sc">~</span> grupos_kmeans,</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">permutations =</span> <span class="fu">how</span>(<span class="at">nperm =</span> <span class="dv">999</span>, <span class="at">blocks =</span> <span class="cn">NULL</span>),  <span class="co"># ou aumentar nperm = 5000+</span></span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">parallel =</span> cl</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>985.22 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Encerrar cluster</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopCluster</span>(cl)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibir o resultado</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>resultado_permanova</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Terms added sequentially (first to last)
Permutation: free
Number of permutations: 999

adonis2(formula = dist_matrix ~ grupos_kmeans, permutations = how(nperm = 999, blocks = NULL), parallel = cl)
                Df SumOfSqs      R2      F Pr(&gt;F)    
grupos_kmeans    2    52535 0.21586 1196.1  0.001 ***
Residual      8690   190841 0.78414                  
Total         8692   243376 1.00000                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir número de núcleos (ex: todos menos 1)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>n_cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Registrar o cluster</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> <span class="fu">makeCluster</span>(n_cores)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar se grupos estão no formato adequado</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>grupos_som <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(grupos_som)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular a matriz de distâncias (ou usar diretamente no adonis2)</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>dist_matrix <span class="ot">&lt;-</span> <span class="fu">dist</span>(dados_prep, <span class="at">method =</span> <span class="st">"euclidean"</span>)</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Executar PERMANOVA com paralelização</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>resultado_permanova <span class="ot">&lt;-</span> <span class="fu">adonis2</span>(</span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> dist_matrix <span class="sc">~</span> grupos_som,</span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">permutations =</span> <span class="fu">how</span>(<span class="at">nperm =</span> <span class="dv">999</span>, <span class="at">blocks =</span> <span class="cn">NULL</span>),  <span class="co"># ou aumentar nperm = 5000+</span></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">parallel =</span> cl</span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1035.25 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Encerrar cluster</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopCluster</span>(cl)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibir o resultado</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>resultado_permanova</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Terms added sequentially (first to last)
Permutation: free
Number of permutations: 999

adonis2(formula = dist_matrix ~ grupos_som, permutations = how(nperm = 999, blocks = NULL), parallel = cl)
             Df SumOfSqs      R2      F Pr(&gt;F)    
grupos_som    3    72674 0.29861 1233.1  0.001 ***
Residual   8689   170702 0.70139                  
Total      8692   243376 1.00000                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Podemos observar que ambos os agrupamentos são estatisticamente significativos (valor-p &lt; 0.001), indicando que há estrutura nos dados, ou seja, os grupos não são aleatórios. O agrupamento por SOM com 4 grupos explica mais variabilidade (29,9%) da estrutura de distâncias do que o K-means com 3 grupos (21,6%). O valor de F também é maior para o SOM (1233.1 vs.&nbsp;1196.1), o que reforça a qualidade da separação em 4 grupos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DBI exige labels inteiros</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>labels_som <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(grupos_som)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>labels_km <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(grupos_kmeans)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>dados_matrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(dados_prep)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular índice Davies-Bouldin</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>dbi_result <span class="ot">&lt;-</span> <span class="fu">intCriteria</span>(<span class="at">traj =</span> dados_matrix, <span class="at">part =</span> labels_som, <span class="at">crit =</span> <span class="st">"all"</span>)</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>dbi_result_km <span class="ot">&lt;-</span> <span class="fu">intCriteria</span>(<span class="at">traj =</span> dados_matrix, <span class="at">part =</span> labels_km, <span class="at">crit =</span> <span class="st">"all"</span>)</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibir resultado</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>dbi_result<span class="sc">$</span>davies_bouldin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.910649</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>dbi_result<span class="sc">$</span>silhouette</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1800618</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>dbi_result_km<span class="sc">$</span>davies_bouldin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.2268</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>dbi_result_km<span class="sc">$</span>silhouette</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1282857</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_silhouette</span>(<span class="fu">silhouette</span>(labels_som, <span class="fu">dist</span>(dados_prep)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cluster size ave.sil.width
1       1 1149          0.19
2       2 3841          0.11
3       3 1874          0.15
4       4 1829          0.26</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_silhouette</span>(<span class="fu">silhouette</span>(labels_km, <span class="fu">dist</span>(dados_prep)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cluster size ave.sil.width
1       1 2795          0.12
2       2 3710          0.19
3       3 2188          0.08</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-43-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Com base nos valores para o índice de Davies-Bouldin (DBI) e índice de Silhueta, podemos fazer a seguinte interpretação comparativa entre dois métodos de clusterização</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Métrica</th>
<th>SOM</th>
<th>K-means</th>
<th>Melhor Método</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Davies-Bouldin (↓)</td>
<td><strong>1.91</strong></td>
<td>2.23</td>
<td>✅ <strong>SOM</strong></td>
</tr>
<tr class="even">
<td>Silhueta (↑)</td>
<td><strong>0.180</strong></td>
<td>0.128</td>
<td>✅ <strong>SOM</strong></td>
</tr>
</tbody>
</table>
<p>Podemos observar que as redes SOM apresentam desempenho superior, possuindo menor DBI (1.91), o que indica que os clusters estão mais compactos e bem separados em comparação ao K-means. Além disso, apresenta maior índice de Silhueta (0.180), o que sugere que os indivíduos estão mais bem alocados dentro de seus clusters com relação à distância entre clusters.</p>
<p>Vale ressaltar que os valores do índice de Silhueta estão próximos de 0.1–0.2, o que indica clusters pouco definidos. Pode haver sobreposição entre grupos, indicando que talvez os dados não possuam estrutura de agrupamento forte.</p>
</section>
<section id="perfis-dos-grupos-gerados" class="level2">
<h2 class="anchored" data-anchor-id="perfis-dos-grupos-gerados">Perfis dos grupos gerados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>dados_com_grupos <span class="ot">&lt;-</span> dados_prep <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grupo_som =</span> <span class="fu">factor</span>(grupos_som))</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>resumo_grupos <span class="ot">&lt;-</span> dados_com_grupos <span class="sc">%&gt;%</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(grupo_som) <span class="sc">%&gt;%</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>grupo_som, <span class="at">names_to =</span> <span class="st">"variavel"</span>, <span class="at">values_to =</span> <span class="st">"media"</span>)</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resumo_grupos, <span class="fu">aes</span>(<span class="at">x =</span> variavel, <span class="at">y =</span> media, <span class="at">color =</span> grupo_som, <span class="at">group =</span> grupo_som)) <span class="sc">+</span></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Perfis Médios por Variável e Grupo (SOM)"</span>, <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Média"</span>) <span class="sc">+</span></span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_cluster_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No gráfico acima, cada linha representa um dos 4 grupos gerados pela rede SOM (grupo_som de 1 a 4). O eixo x traz as variáveis originais da base de dados, enquanto que o eixo y representa a média padronizada de cada variável dentro de cada grupo. As diferenças entre as linhas ao longo do eixo x indicam variáveis que mais distinguem os grupos.</p>
<p>Com base no gráfico, destacam-se como importantes na separação entre os grupos SOM:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th>Variável</th>
<th>Observação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ShoppingMall</code></td>
<td>Grupo 1 tem valores visivelmente mais altos.</td>
</tr>
<tr class="even">
<td><code>RoomService</code>, <code>Spa</code>, <code>VRDeck</code></td>
<td>Claramente mais elevados no <strong>grupo 1</strong>, próximos de zero ou negativos nos outros.</td>
</tr>
<tr class="odd">
<td><code>FoodCourt</code></td>
<td>Também destaca o grupo 1 com pico alto.</td>
</tr>
<tr class="even">
<td><code>IsAlone_X1</code></td>
<td>Forte separação: grupo 3 com valor mínimo, grupo 1 e 4 mais elevados.</td>
</tr>
<tr class="odd">
<td><code>HomePlanet_Earth</code></td>
<td>Grupo 2 se diferencia nitidamente dos demais.</td>
</tr>
<tr class="even">
<td><code>HomePlanet_Mars</code></td>
<td>Grupo 1 com valor fortemente negativo (quase -1), indicando ausência.</td>
</tr>
<tr class="odd">
<td><code>Destination_TRAPPIST-1e</code></td>
<td>Variação clara entre os grupos, sobretudo entre 1 e 3.</td>
</tr>
<tr class="even">
<td><code>CryoSleep_TRUE.</code></td>
<td>Separação visível entre grupos 1/3 e 2/4.</td>
</tr>
<tr class="odd">
<td><code>CabinDeck_B</code>, <code>CabinDeck_C</code>, <code>CabinDeck_F</code></td>
<td>Alguns grupos têm picos bem distintos, sugerindo uso diferente das cabines.</td>
</tr>
</tbody>
</table>
<section id="interpretação-geral-dos-grupos" class="level3">
<h3 class="anchored" data-anchor-id="interpretação-geral-dos-grupos">Interpretação geral dos grupos</h3>
<ul>
<li><strong>Grupo 1:</strong> parece composto por passageiros com alto consumo de serviços (<code>RoomService</code>, <code>Spa</code>, <code>VRDeck</code>, <code>FoodCourt</code>, <code>ShoppingMall</code>), geralmente não dormindo em <code>CryoSleep</code>, e com valores extremos em várias variáveis.
<ul>
<li><strong>Perfil:</strong> Passageiros mais velhos, ativos, sociáveis, consumidores de serviços, não em criogenia, principalmente da Terra e viajando para TRAPPIST-1e.</li>
</ul></li>
<li><strong>Grupo 2:</strong> mostra valores mais centrados, destaca-se por <code>HomePlanet_Earth</code> e padrões mais equilibrados.
<ul>
<li><strong>Perfil:</strong> Grupo moderado, com pouca atividade em serviços pagos, viagem equilibrada entre sozinhos e acompanhados, origem majoritária da Terra, mas não se destacam por extremos.</li>
</ul></li>
<li><strong>Grupo 3:</strong> possui vários valores médios negativos, baixa presença de serviços, e maior chance de estar sozinho (<code>IsAlone</code>).
<ul>
<li><strong>Perfil:</strong> Passageiros com perfil econômico, viagem solitária, em criogenia, oriundos de Marte, com destino alternativo.</li>
</ul></li>
<li><strong>Grupo 4:</strong> flutua, mas tem valores mais elevados em algumas categorias como <code>CabinDeck_E</code> e <code>VRDeck</code>.
<ul>
<li><strong>Perfil:</strong> Grupo com forte localização em Deck G, com uso moderado de serviços e perfil híbrido, sem comportamento extremo.</li>
</ul></li>
</ul>
<p>O gráfico evidencia que variáveis relacionadas ao consumo de serviços, plano de viagem (<code>HomePlanet</code>/<code>Destination</code>) e características de cabine são as principais responsáveis pela separação dos grupos SOM. Isso demonstra que a SOM foi eficaz em capturar padrões de comportamento e perfil de passageiros.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("http:\/\/professortp\.com\.br\/est125\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2026, Tiago Pereira</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/tiagomartin/est125/edit/main/analise_dados/space_titanic_cluster.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/tiagomartin/est125/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Página construída usando <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>