<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Criando um sistema de recomendação baseado em regras de associação usando a base de dados Space Titanic – EST125 - Introdução à Mineração de Dados</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-748b535e376f14d4692bf2b2e5fd6380.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b09848b6287391c45069fed345a57cb2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-e9f3ba5fbee03b112b18b9666ab66a2c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-b09848b6287391c45069fed345a57cb2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<link href="../site_libs/vis-9.1.0/vis-network.min.css" rel="stylesheet">

<script src="../site_libs/vis-9.1.0/vis-network.min.js"></script>

<script src="../site_libs/visNetwork-binding-2.1.2/visNetwork.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Criando um sistema de recomendação baseado em regras de associação usando a base de dados Space Titanic – EST125 - Introdução à Mineração de Dados">
<meta property="og:description" content="Homepage da disciplina EST125 - Introdução à Mineração de Dados, 2025/1.">
<meta property="og:image" content="http://professortp.com.br/est1125/analise_dados/space_titanic_regras_files/figure-html/unnamed-chunk-8-1.png">
<meta property="og:site_name" content="EST125 - Introdução à Mineração de Dados">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Criando um sistema de recomendação baseado em regras de associação usando a base de dados Space Titanic</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://github.com/tiagomartin/est125" title="github" class="quarto-navigation-tool px-1" aria-label="github"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aulas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análise de Dados</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cronograma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cronograma da Disciplina</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Material Complementar</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../plano.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plano de Ensino</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../projeto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projeto Avaliativo</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#o-que-são-regras-de-associação" id="toc-o-que-são-regras-de-associação" class="nav-link active" data-scroll-target="#o-que-são-regras-de-associação">O que são Regras de Associação?</a></li>
  <li><a href="#o-algoritmo-apriori" id="toc-o-algoritmo-apriori" class="nav-link" data-scroll-target="#o-algoritmo-apriori">O Algoritmo Apriori</a></li>
  <li><a href="#mãos-à-obra-construindo-nosso-sistema-no-r" id="toc-mãos-à-obra-construindo-nosso-sistema-no-r" class="nav-link" data-scroll-target="#mãos-à-obra-construindo-nosso-sistema-no-r">Mãos à obra: Construindo nosso Sistema no R</a></li>
  <li><a href="#pacotes-utilizados" id="toc-pacotes-utilizados" class="nav-link" data-scroll-target="#pacotes-utilizados">Pacotes utilizados</a></li>
  <li><a href="#leitura-dos-dados" id="toc-leitura-dos-dados" class="nav-link" data-scroll-target="#leitura-dos-dados">Leitura dos dados</a>
  <ul class="collapse">
  <li><a href="#o-que-podemos-esperar-do-apriori" id="toc-o-que-podemos-esperar-do-apriori" class="nav-link" data-scroll-target="#o-que-podemos-esperar-do-apriori">O que podemos esperar do Apriori?</a></li>
  <li><a href="#o-padrão-principal-homeplanet-gastos-baixos---cabin-deck-g" id="toc-o-padrão-principal-homeplanet-gastos-baixos---cabin-deck-g" class="nav-link" data-scroll-target="#o-padrão-principal-homeplanet-gastos-baixos---cabin-deck-g">O Padrão Principal: HomePlanet + Gastos Baixos -&gt; Cabin Deck G</a></li>
  <li><a href="#o-papel-da-variável-vip" id="toc-o-papel-da-variável-vip" class="nav-link" data-scroll-target="#o-papel-da-variável-vip">O Papel da Variável VIP</a></li>
  </ul></li>
  <li><a href="#construindo-um-sistema-de-recomendação-simples-baseado-em-regras-de-associação" id="toc-construindo-um-sistema-de-recomendação-simples-baseado-em-regras-de-associação" class="nav-link" data-scroll-target="#construindo-um-sistema-de-recomendação-simples-baseado-em-regras-de-associação">Construindo um sistema de recomendação simples, baseado em regras de associação</a>
  <ul class="collapse">
  <li><a href="#análise-das-recomendações" id="toc-análise-das-recomendações" class="nav-link" data-scroll-target="#análise-das-recomendações">Análise das Recomendações</a></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão">Conclusão</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/tiagomartin/est125/edit/main/analise_dados/space_titanic_regras.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/tiagomartin/est125/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Criando um sistema de recomendação baseado em regras de associação usando a base de dados Space Titanic</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Já pararam para pensar em como o Netflix sugere o próximo filme ou o Spotify acerta em cheio na sua playlist semanal? Por trás dessas “mágicas”, existem algoritmos poderosos. Hoje, vamos desvendar um deles: as regras de associação.</p>
<p>Nesta análise, vamos mergulhar na base de dados Space Titanic do Kaggle para construir um sistema de recomendação simples, mas eficaz, baseado no famoso algoritmo Apriori.</p>
<section id="o-que-são-regras-de-associação" class="level2">
<h2 class="anchored" data-anchor-id="o-que-são-regras-de-associação">O que são Regras de Associação?</h2>
<p>As regras de associação são uma técnica de aprendizado de máquina não supervisionado usada para descobrir relações interessantes entre itens em um grande conjunto de dados. Pense em uma cesta de compras de supermercado: se um cliente compra pão e manteiga, qual a probabilidade de ele também comprar geleia?</p>
<p>Uma regra de associação é expressa na forma:</p>
<p><span class="math display">\[A \Longrightarrow B\]</span></p>
<p>em que <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> são conjuntos de itens. <span class="math inline">\(A\)</span> é chamado de antecedente e <span class="math inline">\(B\)</span> é o consequente. Para avaliar a força de uma regra, usamos três métricas principais:</p>
<ul>
<li><strong>Suporte (sup):</strong> A proporção de transações que contêm tanto o antecedente quanto o consequente. Um suporte alto indica que a combinação de itens é frequente no conjunto de dados.</li>
</ul>
<p><span class="math display">\[sup(A∪B)= \dfrac{\text{Número de transações com A e B}}{\text{Número total de transações}}\]</span></p>
<ul>
<li><strong>Confiança (conf):</strong> A probabilidade de um item <span class="math inline">\(B\)</span> ser comprado, dado que um item <span class="math inline">\(A\)</span> já foi comprado.</li>
</ul>
<p><span class="math display">\[conf(A \Longrightarrow B) = \dfrac{sup(A∪B)}{sup(A)}\]</span></p>
<ul>
<li><strong>Lift:</strong> A métrica mais interessante para regras de associação! O lift mede o quão mais provável é que <span class="math inline">\(B\)</span> seja comprado quando <span class="math inline">\(A\)</span> é comprado, em comparação com a probabilidade de <span class="math inline">\(B\)</span> ser comprado sozinho.
<ul>
<li>Se Lift &gt; 1, a presença de <span class="math inline">\(A\)</span> aumenta a probabilidade de <span class="math inline">\(B\)</span>.</li>
<li>Se Lift = 1, <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> são independentes.</li>
<li>Se Lift &lt; 1, a presença de <span class="math inline">\(A\)</span> diminui a probabilidade de <span class="math inline">\(B\)</span>.</li>
</ul></li>
</ul>
<p><span class="math display">\[Lift(A \Longrightarrow B) = \dfrac{conf(A \Longrightarrow B)}{sup(B)} = \dfrac{sup(A∪B)}{sup(A) \times sup(B)}\]</span></p>
</section>
<section id="o-algoritmo-apriori" class="level2">
<h2 class="anchored" data-anchor-id="o-algoritmo-apriori">O Algoritmo Apriori</h2>
<p>O algoritmo Apriori é a espinha dorsal da mineração de regras de associação. Ele funciona em duas etapas principais:</p>
<ol type="1">
<li><p><strong>Encontrar Conjuntos de Itens Frequentes:</strong> O algoritmo identifica conjuntos de itens que aparecem juntos com uma frequência maior que um suporte mínimo pré-definido. Para evitar a explosão de combinações, ele usa a propriedade “anti-monotônica”: se um conjunto de itens não é frequente, nenhum de seus superconjuntos pode ser frequente.</p></li>
<li><p><strong>Gerar Regras de Associação:</strong> A partir dos conjuntos de itens frequentes, ele gera regras de associação e calcula as métricas de confiança e lift.</p></li>
</ol>
</section>
<section id="mãos-à-obra-construindo-nosso-sistema-no-r" class="level2">
<h2 class="anchored" data-anchor-id="mãos-à-obra-construindo-nosso-sistema-no-r">Mãos à obra: Construindo nosso Sistema no R</h2>
<p>Vamos usar a base de dados do Kaggle Space Titanic. Nosso objetivo é criar um “sistema de recomendação” para prever quais características (por exemplo, status de transporte, acomodação) estão associadas umas às outras. Para isso, precisamos transformar nossos dados em um formato de transações, onde cada linha é um “cesto de compras” do passageiro.</p>
</section>
<section id="pacotes-utilizados" class="level2">
<h2 class="anchored" data-anchor-id="pacotes-utilizados">Pacotes utilizados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>load <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  new.pkg <span class="ot">&lt;-</span> pkg[<span class="sc">!</span>(pkg <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(new.pkg))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">install.packages</span>(new.pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sapply</span>(pkg, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Pacotes utilizados nessa análise</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>packages <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"tidymodels"</span>, <span class="st">"arules"</span>, <span class="st">"arulesViz"</span>, <span class="st">"funModeling"</span>, <span class="st">"tictoc"</span>, <span class="st">"future"</span>, <span class="st">"doFuture"</span>, <span class="st">"progressr"</span>, <span class="st">"recommenderlab"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(packages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     tidyverse     tidymodels         arules      arulesViz    funModeling 
          TRUE           TRUE           TRUE           TRUE           TRUE 
        tictoc         future       doFuture      progressr recommenderlab 
          TRUE           TRUE           TRUE           TRUE           TRUE </code></pre>
</div>
</div>
</section>
<section id="leitura-dos-dados" class="level2">
<h2 class="anchored" data-anchor-id="leitura-dos-dados">Leitura dos dados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/tiagomartin/est125/refs/heads/main/dados/space_titanic.csv"</span>, <span class="at">na.strings =</span> <span class="st">""</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,606
Columns: 14
$ PassengerId  &lt;chr&gt; "0001_01", "0002_01", "0003_01", "0003_02", "0004_01", "0…
$ HomePlanet   &lt;chr&gt; "Europa", "Earth", "Europa", "Europa", "Earth", "Earth", …
$ CryoSleep    &lt;chr&gt; "False", "False", "False", "False", "False", "False", "Fa…
$ Cabin        &lt;chr&gt; "B/0/P", "F/0/S", "A/0/S", "A/0/S", "F/1/S", "F/0/P", "F/…
$ Destination  &lt;chr&gt; "TRAPPIST-1e", "TRAPPIST-1e", "TRAPPIST-1e", "TRAPPIST-1e…
$ Age          &lt;dbl&gt; 39, 24, 58, 33, 16, 44, 26, 35, 14, 45, 32, 48, 28, 24, 4…
$ VIP          &lt;chr&gt; "False", "False", "True", "False", "False", "False", "Fal…
$ RoomService  &lt;dbl&gt; 0, 109, 43, 0, 303, 0, 42, 0, 0, 39, 73, 719, 8, 0, 0, 0,…
$ FoodCourt    &lt;dbl&gt; 0, 9, 3576, 1283, 70, 483, 1539, 785, 0, 7295, 0, 1, 974,…
$ ShoppingMall &lt;dbl&gt; 0, 25, 0, 371, 151, 0, 3, 17, 0, 589, 1123, 65, 12, 0, 0,…
$ Spa          &lt;dbl&gt; 0, 549, 6715, 3329, 565, 291, 0, 216, 0, 110, 0, 0, 2, 0,…
$ VRDeck       &lt;dbl&gt; 0, 44, 49, 193, 2, 0, 0, 0, 0, 124, 113, 24, 7, 637, 0, 0…
$ Name         &lt;chr&gt; "Maham Ofracculy", "Juanna Vines", "Altark Susent", "Sola…
$ Transported  &lt;chr&gt; "False", "True", "False", "False", "True", "True", "True"…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Engenharia de variáveis</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">=</span> dados <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(Cabin, <span class="fu">c</span>(<span class="st">"CabinDeck"</span>, <span class="st">"CabinNum"</span>, <span class="st">"CabinSide"</span>), <span class="at">sep =</span> <span class="st">"/"</span>, <span class="at">remove =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CabinDeck =</span> <span class="fu">as.factor</span>(CabinDeck),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">CabinSide =</span> <span class="fu">as.factor</span>(CabinSide))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Antes de iniciarmos a modelagem, é essencial que os dados estejam no formato correto. O algoritmo Apriori, que usamos para regras de associação, trabalha exclusivamente com dados categóricos. Algumas variáveis originais, como <code>Age</code>, <code>RoomService</code> e <code>Spa</code>, são contínuas e precisam ser transformadas. Para isso, usamos a função <code>recipe()</code> encadeada ao pacote <code>tidymodels</code> para definir nosso <em>blueprint</em> de pré-processamento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criar a receita para o pré-processamento</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>recipe_obj <span class="ot">&lt;-</span> <span class="fu">recipe</span>(Transported <span class="sc">~</span> ., <span class="at">data =</span> dados) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Transformar 'Age' em categorias (Jovem, Adulto, Idoso)</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(<span class="at">Age_cat =</span> <span class="fu">ifelse</span>(Age <span class="sc">&lt;</span> <span class="dv">18</span>, <span class="st">"Jovem"</span>, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                               <span class="fu">ifelse</span>(Age <span class="sc">&lt;=</span> <span class="dv">50</span>, <span class="st">"Adulto"</span>, <span class="st">"Idoso"</span>)), </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">RoomService_cat =</span> <span class="fu">ifelse</span>(RoomService <span class="sc">&lt;=</span> <span class="fu">quantile</span>(RoomService, <span class="fl">0.33</span>), <span class="st">"Baixo"</span>, </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">ifelse</span>(RoomService <span class="sc">&lt;=</span> <span class="fu">quantile</span>(RoomService, <span class="fl">0.66</span>), <span class="st">"Médio"</span>, <span class="st">"Alto"</span>)),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">FoodCourt_cat =</span> <span class="fu">ifelse</span>(FoodCourt <span class="sc">&lt;=</span> <span class="fu">quantile</span>(FoodCourt, <span class="fl">0.33</span>), <span class="st">"Baixo"</span>, </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ifelse</span>(FoodCourt <span class="sc">&lt;=</span> <span class="fu">quantile</span>(FoodCourt, <span class="fl">0.66</span>), <span class="st">"Médio"</span>, <span class="st">"Alto"</span>)),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">ShoppingMall_cat =</span> <span class="fu">ifelse</span>(ShoppingMall <span class="sc">&lt;=</span> <span class="fu">quantile</span>(ShoppingMall, <span class="fl">0.33</span>), <span class="st">"Baixo"</span>, </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">ifelse</span>(ShoppingMall <span class="sc">&lt;=</span> <span class="fu">quantile</span>(ShoppingMall, <span class="fl">0.66</span>), <span class="st">"Médio"</span>, <span class="st">"Alto"</span>)),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Spa_cat =</span> <span class="fu">ifelse</span>(Spa <span class="sc">&lt;=</span> <span class="fu">quantile</span>(Spa, <span class="fl">0.33</span>), <span class="st">"Baixo"</span>, </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">ifelse</span>(Spa <span class="sc">&lt;=</span> <span class="fu">quantile</span>(Spa, <span class="fl">0.66</span>), <span class="st">"Médio"</span>, <span class="st">"Alto"</span>)),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">VRDeck_cat =</span> <span class="fu">ifelse</span>(VRDeck <span class="sc">&lt;=</span> <span class="fu">quantile</span>(VRDeck, <span class="fl">0.33</span>), <span class="st">"Baixo"</span>, </span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">ifelse</span>(VRDeck <span class="sc">&lt;=</span> <span class="fu">quantile</span>(VRDeck, <span class="fl">0.66</span>), <span class="st">"Médio"</span>, <span class="st">"Alto"</span>))</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(Name, PassengerId, CabinNum, Age, RoomService, FoodCourt, ShoppingMall, Spa, VRDeck) <span class="sc">%&gt;%</span> </span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_string2factor</span>(<span class="fu">all_string</span>()) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Após definirmos nosso plano de pré-processamento com o <code>recipe</code>, a próxima etapa é aplicar esse plano aos nossos dados. O objeto <code>recipe_obj</code> que criamos anteriormente é, na verdade, uma “receita” de como cozinhar os dados, mas os dados ainda não foram “cozinhados”. É aqui que entram as funções <code>prep()</code> e <code>bake()</code>.</p>
<ol type="1">
<li><p><code>prep(recipe_obj, training = dados):</code> Esta função é o coração do processo. Ela prepara a receita, o que significa que ela “aprende” as transformações a partir dos seus dados de treinamento. Por exemplo, ao rodar o <code>prep</code>, a receita vai calcular os quantis para as variáveis <code>RoomService</code>, <code>FoodCourt</code>, etc., com base na distribuição dos dados (<code>training = dados</code>). Esse passo garante que as transformações sejam consistentes em todos os seus conjuntos de dados (treino e teste), evitando vazamento de informações.</p></li>
<li><p><code>bake(dados_processados, new_data = NULL):</code> Com a receita já preparada, a função <code>bake</code> aplica as transformações aos dados. No nosso caso, ao passar <code>new_data = NULL</code>, estamos pedindo para aplicar as transformações ao mesmo conjunto de dados que foi usado no <code>prep</code>.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preparar e aplicar a receita no conjunto de dados</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>dados_processados <span class="ot">&lt;-</span> <span class="fu">prep</span>(recipe_obj, <span class="at">training =</span> dados)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar a receita no conjunto de dados</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>dados_transf <span class="ot">&lt;-</span> <span class="fu">bake</span>(dados_processados, <span class="at">new_data =</span> <span class="cn">NULL</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>dados_transf <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,606
Columns: 13
$ HomePlanet       &lt;fct&gt; Europa, Earth, Europa, Europa, Earth, Earth, Earth, E…
$ CryoSleep        &lt;fct&gt; False, False, False, False, False, False, False, Fals…
$ CabinDeck        &lt;fct&gt; B, F, A, A, F, F, F, F, B, B, F, G, F, F, F, G, F, E,…
$ CabinSide        &lt;fct&gt; P, S, S, S, S, P, S, S, P, P, P, S, P, P, P, P, P, S,…
$ Destination      &lt;fct&gt; TRAPPIST-1e, TRAPPIST-1e, TRAPPIST-1e, TRAPPIST-1e, T…
$ VIP              &lt;fct&gt; False, False, True, False, False, False, False, False…
$ Transported      &lt;fct&gt; False, True, False, False, True, True, True, True, Tr…
$ Age_cat          &lt;fct&gt; Adulto, Adulto, Idoso, Adulto, Jovem, Adulto, Adulto,…
$ RoomService_cat  &lt;fct&gt; Baixo, Alto, Alto, Baixo, Alto, Baixo, Alto, Baixo, B…
$ FoodCourt_cat    &lt;fct&gt; Baixo, Alto, Alto, Alto, Alto, Alto, Alto, Alto, Baix…
$ ShoppingMall_cat &lt;fct&gt; Baixo, Alto, Baixo, Alto, Alto, Baixo, Alto, Alto, Ba…
$ Spa_cat          &lt;fct&gt; Baixo, Alto, Alto, Alto, Alto, Alto, Baixo, Alto, Bai…
$ VRDeck_cat       &lt;fct&gt; Baixo, Alto, Alto, Alto, Médio, Baixo, Baixo, Baixo, …</code></pre>
</div>
</div>
<p>Ao final, a variável <code>dados_transf</code> conterá um novo dataframe com todas as transformações aplicadas: as variáveis contínuas foram discretizadas, as colunas desnecessárias foram removidas e as variáveis de texto foram convertidas para fatores. A chamada <code>glimpse()</code> nos permite dar uma olhada rápida na nova estrutura dos dados, confirmando que tudo foi processado conforme o esperado e que agora estamos prontos para aplicar o algoritmo Apriori. O pacote <code>arules</code>, que contém o algoritmo Apriori, exige que os dados estejam em um formato específico: um objeto de transações. A função <code>as()</code> aplicada ao nosso dataframe <code>dados_transf</code> e especificada como <code>transactions</code> transforma cada linha do dataframe em uma “cesta de compras” e cada coluna em um “item”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converter o dataset processado para o formato de transações</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>dados_transacoes <span class="ot">&lt;-</span> <span class="fu">as</span>(dados_transf, <span class="st">"transactions"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Podemos então, visualizar as primeiras transações e ter certeza de que a conversão foi feita corretamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificando as primeiras transações</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(dados_transacoes[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    items                      transactionID
[1] {HomePlanet=Europa,                     
     CryoSleep=False,                       
     CabinDeck=B,                           
     CabinSide=P,                           
     Destination=TRAPPIST-1e,               
     VIP=False,                             
     Transported=False,                     
     Age_cat=Adulto,                        
     RoomService_cat=Baixo,                 
     FoodCourt_cat=Baixo,                   
     ShoppingMall_cat=Baixo,                
     Spa_cat=Baixo,                         
     VRDeck_cat=Baixo}                     1
[2] {HomePlanet=Earth,                      
     CryoSleep=False,                       
     CabinDeck=F,                           
     CabinSide=S,                           
     Destination=TRAPPIST-1e,               
     VIP=False,                             
     Transported=True,                      
     Age_cat=Adulto,                        
     RoomService_cat=Alto,                  
     FoodCourt_cat=Alto,                    
     ShoppingMall_cat=Alto,                 
     Spa_cat=Alto,                          
     VRDeck_cat=Alto}                      2
[3] {HomePlanet=Europa,                     
     CryoSleep=False,                       
     CabinDeck=A,                           
     CabinSide=S,                           
     Destination=TRAPPIST-1e,               
     VIP=True,                              
     Transported=False,                     
     Age_cat=Idoso,                         
     RoomService_cat=Alto,                  
     FoodCourt_cat=Alto,                    
     ShoppingMall_cat=Baixo,                
     Spa_cat=Alto,                          
     VRDeck_cat=Alto}                      3</code></pre>
</div>
</div>
<p>Por fim, geramos um gráfico que mostra a frequência dos itens mais comuns. Essa visualização é crucial para entender a distribuição dos nossos dados e nos ajuda a definir um valor de <code>support</code> adequado para o algoritmo Apriori. Itens muito raros não formarão regras fortes, então é bom ver quais são os mais frequentes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">itemFrequencyPlot</span>(dados_transacoes, <span class="at">topN =</span> <span class="dv">20</span>, <span class="at">type =</span> <span class="st">"relative"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="space_titanic_regras_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analisando o gráfico, podemos tirar algumas conclusões importantes sobre os passageiros do Space Titanic:</p>
<ul>
<li><p><strong>Itens Mais Frequentes:</strong> O item mais frequente de longe é <code>VIP=False</code>. Isso significa que a grande maioria dos passageiros não era VIP. Em seguida, temos <code>Age_cat=Adulto</code>, indicando que a maior parte da tripulação estava na faixa etária adulta, e <code>Destination=TRAPPIST-1e</code>, que era o destino mais comum.</p></li>
<li><p><strong>Foco nas Variáveis de Gastos:</strong> As variáveis de gastos (<code>RoomService</code>, <code>FoodCourt</code>, <code>ShoppingMall</code>, <code>Spa</code>, <code>VRDeck</code>), que discretizamos em categorias, aparecem com maior frequência na categoria Baixo. Isso sugere que a maioria dos passageiros não gastou muito nesses serviços. Note que <code>ShoppingMall_cat=Baixo</code>, <code>RoomService_cat=Baixo</code>, <code>FoodCourt_cat=Baixo</code>, <code>VRDeck_cat=Baixo</code> e <code>Spa_cat=Baixo</code> estão todos entre os itens mais frequentes.</p></li>
<li><p><strong>Variáveis-Chave de Transporte:</strong> A variável <code>Transported=False</code> e <code>Transported=True</code> aparecem com frequências muito parecidas, por volta de 50%. Isso confirma que o dataset está bem balanceado em relação ao nosso alvo, que é a variável <code>Transported</code>. A ligeira diferença pode ser importante, mas o balanço é bom para a modelagem.</p></li>
</ul>
<section id="o-que-podemos-esperar-do-apriori" class="level3">
<h3 class="anchored" data-anchor-id="o-que-podemos-esperar-do-apriori">O que podemos esperar do Apriori?</h3>
<p>Itens com alta frequência, como <code>VIP=False</code> e <code>Age_cat=Adulto</code>, terão um suporte alto. Por isso, ao rodar o algoritmo Apriori, é provável que vejamos muitas regras de associação que envolvam esses itens. Itens menos frequentes, como as categorias Alto de gastos, só aparecerão em regras se tiverem uma associação muito forte com outros itens.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plan</span>(multisession, <span class="at">workers =</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoFuture</span>()</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">handlers</span>(<span class="st">"txtprogressbar"</span>)  <span class="co"># ou "progress"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">with_progress</span>({</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicando o algoritmo Apriori para encontrar regras de associação</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>regras <span class="ot">&lt;-</span> <span class="fu">apriori</span>(dados_transacoes, </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">parameter =</span> <span class="fu">list</span>(<span class="at">supp =</span> <span class="fl">0.2</span>, <span class="at">conf =</span> <span class="fl">0.8</span>, <span class="at">target =</span> <span class="st">"rules"</span>))</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Apriori

Parameter specification:
 confidence minval smax arem  aval originalSupport maxtime support minlen
        0.8    0.1    1 none FALSE            TRUE       5     0.2      1
 maxlen target  ext
     10  rules TRUE

Algorithmic control:
 filter tree heap memopt load sort verbose
    0.1 TRUE TRUE  FALSE TRUE    2    TRUE

Absolute minimum support count: 1321 

set item appearances ...[0 item(s)] done [0.00s].
set transactions ...[40 item(s), 6606 transaction(s)] done [0.00s].
sorting and recoding items ... [25 item(s)] done [0.00s].
creating transaction tree ... done [0.00s].
checking subsets of size 1 2 3 4 5 6 7 8 done [0.01s].
writing ... [2911 rule(s)] done [0.00s].
creating S4 object  ... done [0.00s].</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.03 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vamos ordenar as regras por 'lift' para encontrar as associações mais interessantes</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>regras_sorted <span class="ot">&lt;-</span> <span class="fu">sort</span>(regras, <span class="at">by =</span> <span class="st">"lift"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspecionar as 10 melhores regras</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(<span class="fu">head</span>(regras_sorted, <span class="at">n =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     lhs                          rhs             support confidence  coverage     lift count
[1]  {HomePlanet=Earth,                                                                      
      FoodCourt_cat=Baixo,                                                                   
      ShoppingMall_cat=Baixo,                                                                
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2026945  0.9260028 0.2188919 3.100443  1339
[2]  {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      FoodCourt_cat=Baixo,                                                                   
      ShoppingMall_cat=Baixo,                                                                
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2026945  0.9260028 0.2188919 3.100443  1339
[3]  {HomePlanet=Earth,                                                                      
      RoomService_cat=Baixo,                                                                 
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2025431  0.9195876 0.2202543 3.078964  1338
[4]  {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      RoomService_cat=Baixo,                                                                 
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2025431  0.9195876 0.2202543 3.078964  1338
[5]  {HomePlanet=Earth,                                                                      
      ShoppingMall_cat=Baixo,                                                                
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2022404  0.9188446 0.2201029 3.076476  1336
[6]  {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      ShoppingMall_cat=Baixo,                                                                
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2022404  0.9188446 0.2201029 3.076476  1336
[7]  {HomePlanet=Earth,                                                                      
      RoomService_cat=Baixo,                                                                 
      ShoppingMall_cat=Baixo,                                                                
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2028459  0.9184373 0.2208598 3.075112  1340
[8]  {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      RoomService_cat=Baixo,                                                                 
      ShoppingMall_cat=Baixo,                                                                
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2028459  0.9184373 0.2208598 3.075112  1340
[9]  {HomePlanet=Earth,                                                                      
      FoodCourt_cat=Baixo,                                                                   
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2023918  0.9176390 0.2205571 3.072439  1337
[10] {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      FoodCourt_cat=Baixo,                                                                   
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2023918  0.9176390 0.2205571 3.072439  1337</code></pre>
</div>
</div>
<p>Observando as regras, podemos notar alguns padrões muito claros e significativos sobre os passageiros do Space Titanic.</p>
</section>
<section id="o-padrão-principal-homeplanet-gastos-baixos---cabin-deck-g" class="level3">
<h3 class="anchored" data-anchor-id="o-padrão-principal-homeplanet-gastos-baixos---cabin-deck-g">O Padrão Principal: HomePlanet + Gastos Baixos -&gt; Cabin Deck G</h3>
<p>A característica mais notável é que a grande maioria das regras aponta para a mesma conclusão: passageiros que vêm do planeta Terra e têm gastos baixos em diversos serviços a bordo (<code>RoomService</code>, <code>FoodCourt</code>, <code>ShoppingMall</code>, <code>Spa</code>, <code>VRDeck</code>) tendem a estar localizados na cabine do Deck G.</p>
<ul>
<li><strong>Exemplo de Regra ([1]):</strong> <code>{HomePlanet=Earth, FoodCourt_cat=Baixo, ShoppingMall_cat=Baixo, VRDeck_cat=Baixo} =&gt; {CabinDeck=G}</code>.
<ul>
<li><strong>Suporte (0.202):</strong> Essa regra aparece em aproximadamente 20,2% de todas as transações, o que é um valor alto e indica que a combinação de <code>HomePlanet=Earth</code> com gastos baixos e a cabine no <code>Deck=G</code> é bastante comum.</li>
<li><strong>Confiança (0.926):</strong> A confiança de 92,6% é extremamente alta. Isso significa que, se um passageiro é do planeta Terra e tem gastos baixos nos serviços listados, a probabilidade de ele estar no Deck G é de 92,6%.</li>
<li><strong>Lift (3.100):</strong> O lift de 3,1 é a métrica mais importante aqui. Ele nos diz que a probabilidade de um passageiro que vem da Terra e gasta pouco estar no Deck G é 3,1 vezes maior do que a probabilidade de um passageiro qualquer estar no Deck G. Isso indica que a associação não é aleatória; ela é forte e significativa.</li>
<li><strong>coverage (0.218):</strong> Isso significa que aproximadamente 21,8% de todos os passageiros se encaixavam nas condições do antecedente (<code>HomePlanet=Earth, FoodCourt_cat=Baixo, ShoppingMall_cat=Baixo, VRDeck_cat=Baixo</code>).</li>
<li><strong>count (1339):</strong> Significa que 1339 passageiros se encaixavam em todas as condições da regra: eles vieram da Terra, tiveram gastos baixos nos serviços listados e estavam na cabine do Deck G.</li>
</ul></li>
</ul>
</section>
<section id="o-papel-da-variável-vip" class="level3">
<h3 class="anchored" data-anchor-id="o-papel-da-variável-vip">O Papel da Variável VIP</h3>
<p>Outro ponto que salta aos olhos é a presença da variável <code>VIP=False</code> em quase todas as regras. As regras ímpares (1, 3, 5, etc.) são seguidas por regras pares idênticas, mas com o antecedente <code>VIP=False</code> adicionado. No entanto, os valores de <code>support</code>, <code>confidence</code>, <code>coverage</code> e <code>lift</code> são exatamente os mesmos.</p>
<section id="por-que-isso-acontece" class="level4">
<h4 class="anchored" data-anchor-id="por-que-isso-acontece">Por que isso acontece?</h4>
<p>O gráfico de frequência de itens que vimos anteriormente já nos mostrou que <code>VIP=False</code> era um dos itens mais frequentes, com uma frequência acima de 90%.</p>
<p>O algoritmo Apriori encontra as regras mais fortes. Como a maioria esmagadora dos passageiros não era VIP, a inclusão de <code>VIP=False</code> nos antecedentes não altera a proporção de transações que satisfazem a regra. Em essência, a presença de <code>VIP=False</code> é tão comum que se torna quase redundante.</p>
<p>Isso é um bom insight sobre os dados: a variável <code>VIP</code> não é um fator importante para determinar a cabine no Deck G, pois a maioria dos passageiros, sejam eles VIP ou não, já se encaixam nas outras condições da regra.</p>
<p>Agora que já exploramos as regras de associação gerais, vamos focar em um objetivo mais específico: entender quais características dos passageiros estão mais fortemente associadas ao seu status de transporte (<code>Transported=True</code>).</p>
<p>Para isso, usamos um truque muito útil na função <code>apriori()</code>: o parâmetro <code>appearance</code>. Ao usar <code>appearance = list(rhs = "Transported=True", default = "lhs")</code>, estamos direcionando o algoritmo para que ele só procure por regras que tenham <code>Transported=True</code> no consequente (<code>rhs</code>). Isso nos permite criar um “sistema de recomendação” que nos diz “se um passageiro tem as seguintes características, ele provavelmente foi transportado”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>regras_transported <span class="ot">&lt;-</span> <span class="fu">apriori</span>(dados_transacoes,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">parameter =</span> <span class="fu">list</span>(<span class="at">support =</span> <span class="fl">0.2</span>, <span class="at">confidence =</span> <span class="fl">0.8</span>, <span class="at">minlen =</span> <span class="dv">2</span>),</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">appearance =</span> <span class="fu">list</span>(<span class="at">rhs =</span> <span class="st">"Transported=True"</span>, <span class="at">default =</span> <span class="st">"lhs"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Apriori

Parameter specification:
 confidence minval smax arem  aval originalSupport maxtime support minlen
        0.8    0.1    1 none FALSE            TRUE       5     0.2      2
 maxlen target  ext
     10  rules TRUE

Algorithmic control:
 filter tree heap memopt load sort verbose
    0.1 TRUE TRUE  FALSE TRUE    2    TRUE

Absolute minimum support count: 1321 

set item appearances ...[1 item(s)] done [0.00s].
set transactions ...[40 item(s), 6606 transaction(s)] done [0.00s].
sorting and recoding items ... [25 item(s)] done [0.00s].
creating transaction tree ... done [0.00s].
checking subsets of size 1 2 3 4 5 6 7 8 done [0.00s].
writing ... [64 rule(s)] done [0.00s].
creating S4 object  ... done [0.00s].</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>regras_transported_sorted <span class="ot">&lt;-</span> <span class="fu">sort</span>(regras_transported, <span class="at">by =</span> <span class="st">"lift"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspecionar as 10 melhores regras</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(<span class="fu">head</span>(regras_transported_sorted, <span class="at">n =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     lhs                          rhs                  support confidence  coverage     lift count
[1]  {CryoSleep=True}          =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[2]  {CryoSleep=True,                                                                             
      Spa_cat=Baixo}           =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[3]  {CryoSleep=True,                                                                             
      VRDeck_cat=Baixo}        =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[4]  {CryoSleep=True,                                                                             
      FoodCourt_cat=Baixo}     =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[5]  {CryoSleep=True,                                                                             
      RoomService_cat=Baixo}   =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[6]  {CryoSleep=True,                                                                             
      ShoppingMall_cat=Baixo}  =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[7]  {CryoSleep=True,                                                                             
      Spa_cat=Baixo,                                                                              
      VRDeck_cat=Baixo}        =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[8]  {CryoSleep=True,                                                                             
      FoodCourt_cat=Baixo,                                                                        
      Spa_cat=Baixo}           =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[9]  {CryoSleep=True,                                                                             
      RoomService_cat=Baixo,                                                                      
      Spa_cat=Baixo}           =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905
[10] {CryoSleep=True,                                                                             
      ShoppingMall_cat=Baixo,                                                                     
      Spa_cat=Baixo}           =&gt; {Transported=True} 0.2883742  0.8168954 0.3530124 1.622005  1905</code></pre>
</div>
</div>
<p>Ao analisar as regras, um padrão se destaca de forma clara e dominante: o estado de sono criogênico.</p>
<ul>
<li><strong>Regra Principal:</strong> A primeira e mais importante regra é [1] <code>{CryoSleep=True} =&gt; {Transported=True}</code>. - <strong>support (0.288):</strong> Quase 29% de todos os passageiros foram colocados em sono criogênico E foram transportados. Isso demonstra que essa é uma combinação comum nos dados. - <strong>confidence (0.816):</strong> Se um passageiro foi colocado em sono criogênico, há uma probabilidade de mais de 81% de ele ter sido transportado. Esta é uma previsão muito confiável. - <strong>lift (1.622):</strong> O lift de 1.62 nos diz que a probabilidade de um passageiro ser transportado, sabendo que ele está em sono criogênico, é 1,62 vezes maior do que a probabilidade geral de transporte na nave. Isso confirma que a associação não é aleatória.</li>
</ul>
<p>As regras de <code>[2]</code> a <code>[10]</code> são apenas variações da primeira. Elas adicionam um ou mais itens de gastos baixos (<code>Spa_cat=Baixo</code>, <code>VRDeck_cat=Baixo</code>, etc.) ao antecedente, mas os valores de <code>support</code>, <code>confidence</code>, <code>coverage</code>, <code>lift</code> e <code>count</code> permanecem exatamente os mesmos.</p>
<p>Isso significa que a variável <code>CryoSleep=True</code> sozinha é o fator determinante para a previsão. A adição de outras características, como gastos baixos em serviços, não aumenta a confiança nem a relevância da regra, porque todos os passageiros em sono criogênico já têm gastos nulos ou baixos nesses serviços. O algoritmo Apriori está essencialmente nos mostrando que a informação <code>CryoSleep=True</code> já contém, de forma implícita, a informação de que os gastos são baixos.</p>
<p>Agora que identificamos as regras de associação mais relevantes para o transporte de passageiros, a melhor forma de consolidar nosso entendimento é através de uma <strong>visualização</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(regras_transported_sorted[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="at">method =</span> <span class="st">"graph"</span>, <span class="at">engine =</span> <span class="st">"htmlwidget"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="visNetwork html-widget html-fill-item" id="htmlwidget-8668aeeca3eda88722af" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-8668aeeca3eda88722af">{"x":{"nodes":{"id":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],"label":["CryoSleep=True","Transported=True","RoomService_cat=Baixo","FoodCourt_cat=Baixo","ShoppingMall_cat=Baixo","Spa_cat=Baixo","VRDeck_cat=Baixo","rule 1","rule 2","rule 3","rule 4","rule 5","rule 6","rule 7","rule 8","rule 9","rule 10"],"group":[1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2],"value":[1,1,1,1,1,1,1,50.5,50.5,50.5,50.5,50.5,50.5,50.5,50.5,50.5,50.5],"color":["#CBD2FC","#CBD2FC","#CBD2FC","#CBD2FC","#CBD2FC","#CBD2FC","#CBD2FC","#EE9797","#EE9797","#EE9797","#EE9797","#EE9797","#EE9797","#EE9797","#EE9797","#EE9797","#EE9797"],"title":["CryoSleep=True","Transported=True","RoomService_cat=Baixo","FoodCourt_cat=Baixo","ShoppingMall_cat=Baixo","Spa_cat=Baixo","VRDeck_cat=Baixo","<B>[1]<\/B><BR><B>{CryoSleep=True}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 2<BR>id = 1","<B>[2]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;Spa_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 3<BR>id = 2","<B>[3]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;VRDeck_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 3<BR>id = 3","<B>[4]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;FoodCourt_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 3<BR>id = 4","<B>[5]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;RoomService_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 3<BR>id = 5","<B>[6]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;ShoppingMall_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 3<BR>id = 6","<B>[7]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;Spa_cat=Baixo,<BR>&nbsp;&nbsp;VRDeck_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 4<BR>id = 7","<B>[8]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;FoodCourt_cat=Baixo,<BR>&nbsp;&nbsp;Spa_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 4<BR>id = 8","<B>[9]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;RoomService_cat=Baixo,<BR>&nbsp;&nbsp;Spa_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 4<BR>id = 9","<B>[10]<\/B><BR><B>{CryoSleep=True,<BR>&nbsp;&nbsp;ShoppingMall_cat=Baixo,<BR>&nbsp;&nbsp;Spa_cat=Baixo}<\/B><BR>&nbsp;&nbsp; => <B>{Transported=True}<\/B><BR><BR>support = 0.288<BR>confidence = 0.817<BR>coverage = 0.353<BR>lift = 1.62<BR>count = 1900<BR>order = 4<BR>id = 10"],"shape":["box","box","box","box","box","box","box","circle","circle","circle","circle","circle","circle","circle","circle","circle","circle"],"x":[-0.1133712602140903,0.01892566867284518,0.6493562477639709,-0.6685920778113281,1,0.3290196860614745,-1,-0.7504876735109426,0.6766397579444261,-0.7182252393799773,-0.5587451795341367,0.177020678697642,0.3977782537274113,-0.3287867796304488,-0.1613924185755899,0.4624966572567424,0.614389027509088],"y":[-0.02366264854441458,-0.01952350253796287,1,-1,-0.8623205093864997,0.000811968512673511,0.78331084068228,-0.09961403781783973,0.06578469053303504,0.352366775497843,-0.5162624411268579,0.6062031310932803,-0.5842896329344003,0.4035818864256495,-0.5089587873723566,0.4299740607633491,-0.3592860590906164]},"edges":{"from":[1,1,6,1,7,1,4,1,3,1,5,1,6,7,1,4,6,1,3,6,1,5,6,8,9,10,11,12,13,14,15,16,17],"to":[8,9,9,10,10,11,11,12,12,13,13,14,14,14,15,15,15,16,16,16,17,17,17,2,2,2,2,2,2,2,2,2,2],"arrows":["to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to","to"]},"nodesToDataframe":true,"edgesToDataframe":true,"options":{"width":"100%","height":"100%","nodes":{"shape":"dot","physics":false},"manipulation":{"enabled":false},"edges":{"smooth":false},"physics":{"stabilization":false},"interaction":{"hover":true,"zoomSpeed":1}},"groups":["1","2"],"width":null,"height":null,"idselection":{"enabled":true,"style":"width: 150px; height: 26px","useLabels":true,"main":"Select by id"},"byselection":{"enabled":false,"style":"width: 150px; height: 26px","multiple":false,"hideColor":"rgba(200,200,200,0.5)","highlight":false},"main":null,"submain":null,"footer":null,"background":"rgba(0, 0, 0, 0)","igraphlayout":{"type":"square"},"tooltipStay":300,"tooltipStyle":"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);","highlight":{"enabled":true,"hoverNearest":true,"degree":1,"algorithm":"all","hideColor":"rgba(200,200,200,0.5)","labelOnly":true},"collapse":{"enabled":false,"fit":false,"resetHighlight":true,"clusterOptions":null,"keepCoord":true,"labelSuffix":"(cluster)"}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>O gráfico de rede mostra as conexões entre os diferentes itens (nós) e as regras que os conectam (setas).</p>
<ul>
<li><p><strong>Círculos Rosas:</strong> Cada círculo rosa, rotulado como <code>rule 1</code>, <code>rule 2</code>, etc., é a representação de uma regra de associação completa.</p></li>
<li><p><strong>Caixas Azuis:</strong> As caixas azuis, como <code>CryoSleep=True</code> ou <code>Transported=True</code>, representam os itens (variáveis e seus valores).</p></li>
<li><p><strong>Setas que entram no círculo rosa:</strong> Indicam os itens que compõem o antecedente (<code>lhs</code>) da regra. Por exemplo, a seta que sai de <code>CryoSleep=True</code> e vai para o círculo <code>rule 1</code> nos diz que <code>CryoSleep=True</code> é parte do antecedente da Regra 1.</p></li>
<li><p><strong>Setas que saem do círculo rosa:</strong> Indicam o item que é o consequente (<code>rhs</code>) da regra. Vemos que todas as setas saem dos círculos de regras e apontam para a caixa <code>Transported=True</code>. Isso confirma que <code>Transported=True</code> é o consequente de todas as regras que estamos analisando.</p></li>
</ul>
<p>Assim, podemos observar que:</p>
<ul>
<li><p><strong>A Regra Principal (rule 1):</strong> A seta que liga <code>CryoSleep=True</code> ao círculo <code>rule 1</code> e, em seguida, a seta que liga <code>rule 1</code> a <code>Transported=True</code> representa a regra <code>{CryoSleep=True} =&gt; {Transported=True}</code>.</p></li>
<li><p><strong>As Regras Derivadas (rule 2, rule 3, etc.):</strong> As setas que ligam <code>CryoSleep=True</code> e as caixas de gastos baixos aos outros círculos de regras mostram que essas regras têm antecedentes mais complexos, mas ainda resultam na mesma previsão: <code>Transported=True</code>.</p></li>
</ul>
<p>O gráfico é uma ferramenta excelente para visualizar como os itens se conectam através das regras, mostrando que todos os caminhos dos antecedentes convergem para a mesma previsão final.</p>
</section>
</section>
</section>
<section id="construindo-um-sistema-de-recomendação-simples-baseado-em-regras-de-associação" class="level2">
<h2 class="anchored" data-anchor-id="construindo-um-sistema-de-recomendação-simples-baseado-em-regras-de-associação">Construindo um sistema de recomendação simples, baseado em regras de associação</h2>
<p>As regras de associação são uma técnica de mineração de dados que identifica padrões e relações entre itens em um grande conjunto de transações. Pense na clássica análise de cesta de compras: a regra <code>{Pão, Manteiga} =&gt; {Geleia}</code> sugere que clientes que compram pão e manteiga também tendem a comprar geleia.</p>
<p>Um sistema de recomendação usa essa mesma lógica. Em vez de prever a compra de geleia, ele pode prever o interesse em um filme, a alocação de um passageiro em uma cabine, ou a alta probabilidade de um evento acontecer.</p>
<p>O algoritmo Apriori no <code>recommenderlab</code> trabalha com uma matriz esparsa de avaliação binária, um tipo de estrutura de dados otimizado para sistemas de recomendação. Essa matriz representa a presença ou ausência de cada item (colunas) para cada transação ou usuário (linhas). A função <code>as()</code> do pacote <code>arules</code> é perfeita para essa tarefa, pois ela converte o objeto de transações (<code>dados_transacoes</code>) que criamos anteriormente para esse novo formato de forma eficiente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dados_recommender <span class="ot">&lt;-</span> <span class="fu">as</span>(dados_transacoes, <span class="st">"binaryRatingMatrix"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Com os dados agora no formato correto, estamos prontos para a etapa central do nosso sistema de recomendação: a criação do modelo.</p>
<p>O extrato de código a seguir usa a função <code>Recommender()</code> do pacote <code>recommenderlab</code> para treinar nosso modelo de recomendação.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>recom_model <span class="ot">&lt;-</span> <span class="fu">Recommender</span>(<span class="at">data =</span> dados_recommender,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">method =</span> <span class="st">"AR"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">parameter =</span> <span class="fu">list</span>(<span class="at">supp =</span> <span class="fl">0.2</span>, <span class="at">conf =</span> <span class="fl">0.8</span>, <span class="at">maxlen =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ao executar esse código, o <code>recommenderlab</code> irá minerar as regras de associação no nosso conjunto de dados, criando um modelo que pode ser usado para gerar previsões para novos passageiros. Depois de treinar o modelo com <code>Recommender()</code>, as regras de associação descobertas são armazenadas dentro do objeto <code>recom_model</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># O objeto 'recom_model' armazena as regras de associação.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Podemos extrair e inspecionar as regras encontradas.</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>model_details <span class="ot">&lt;-</span> <span class="fu">getModel</span>(recom_model)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>regras_finais <span class="ot">&lt;-</span> model_details<span class="sc">$</span>rule_base</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>regras_finais_sorted <span class="ot">&lt;-</span> <span class="fu">sort</span>(regras_finais, <span class="at">by =</span> <span class="st">"lift"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Vamos inspecionar as regras encontradas pelo recommenderlab</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(<span class="fu">head</span>(regras_finais_sorted, <span class="at">n =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     lhs                          rhs             support confidence  coverage     lift count
[1]  {HomePlanet=Earth,                                                                      
      FoodCourt_cat=Baixo,                                                                   
      ShoppingMall_cat=Baixo,                                                                
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2026945  0.9260028 0.2188919 3.100443  1339
[2]  {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      FoodCourt_cat=Baixo,                                                                   
      ShoppingMall_cat=Baixo,                                                                
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2026945  0.9260028 0.2188919 3.100443  1339
[3]  {HomePlanet=Earth,                                                                      
      RoomService_cat=Baixo,                                                                 
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2025431  0.9195876 0.2202543 3.078964  1338
[4]  {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      RoomService_cat=Baixo,                                                                 
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2025431  0.9195876 0.2202543 3.078964  1338
[5]  {HomePlanet=Earth,                                                                      
      ShoppingMall_cat=Baixo,                                                                
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2022404  0.9188446 0.2201029 3.076476  1336
[6]  {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      ShoppingMall_cat=Baixo,                                                                
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2022404  0.9188446 0.2201029 3.076476  1336
[7]  {HomePlanet=Earth,                                                                      
      RoomService_cat=Baixo,                                                                 
      ShoppingMall_cat=Baixo,                                                                
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2028459  0.9184373 0.2208598 3.075112  1340
[8]  {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      RoomService_cat=Baixo,                                                                 
      ShoppingMall_cat=Baixo,                                                                
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2028459  0.9184373 0.2208598 3.075112  1340
[9]  {HomePlanet=Earth,                                                                      
      FoodCourt_cat=Baixo,                                                                   
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2023918  0.9176390 0.2205571 3.072439  1337
[10] {HomePlanet=Earth,                                                                      
      VIP=False,                                                                             
      FoodCourt_cat=Baixo,                                                                   
      Spa_cat=Baixo,                                                                         
      VRDeck_cat=Baixo}        =&gt; {CabinDeck=G} 0.2023918  0.9176390 0.2205571 3.072439  1337</code></pre>
</div>
</div>
<p>A análise do resultado deste comando nos dará os mesmos insights que obtivemos com o pacote <code>arules</code>, mas agora dentro do fluxo de trabalho do <code>recommenderlab</code>. Nosso objetivo agora é colocar o modelo que treinamos em ação e gerar recomendações. Para isso, iremos “simular” dois novos passageiros para serem apresentados ao nosso sistema de recomendação.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Obter os nomes dos itens do modelo treinado</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>items_names <span class="ot">&lt;-</span> <span class="fu">colnames</span>(dados_recommender)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Criar uma matriz de zeros para todos os passageiros e itens</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Vamos definir o número de passageiros que você quer avaliar</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>num_passageiros <span class="ot">&lt;-</span> <span class="dv">2</span> </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>novos_passageiros_mat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> num_passageiros, <span class="at">ncol =</span> <span class="fu">length</span>(items_names))</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(novos_passageiros_mat) <span class="ot">&lt;-</span> items_names</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(novos_passageiros_mat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Novo_Passageiro_01"</span>, <span class="st">"Novo_Passageiro_02"</span>)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Preencher a matriz com as características de cada passageiro</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Passageiro 1: da Terra, com gastos baixos</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>novos_passageiros_mat[<span class="st">"Novo_Passageiro_01"</span>, <span class="st">"HomePlanet=Earth"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>novos_passageiros_mat[<span class="st">"Novo_Passageiro_01"</span>, <span class="st">"RoomService_cat=Baixo"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>novos_passageiros_mat[<span class="st">"Novo_Passageiro_01"</span>, <span class="st">"FoodCourt_cat=Baixo"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Passageiro 2: VIP, Adulto e em sono criogênico</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>novos_passageiros_mat[<span class="st">"Novo_Passageiro_02"</span>, <span class="st">"VIP=True"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>novos_passageiros_mat[<span class="st">"Novo_Passageiro_02"</span>, <span class="st">"Age_cat=Adulto"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>novos_passageiros_mat[<span class="st">"Novo_Passageiro_02"</span>, <span class="st">"CryoSleep=True"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Converter a matriz consolidada para o formato binaryRatingMatrix</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>novos_passageiros_ratings <span class="ot">&lt;-</span> <span class="fu">as</span>(novos_passageiros_mat, <span class="st">"binaryRatingMatrix"</span>)</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Gerar as recomendações</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>recommendations <span class="ot">&lt;-</span> <span class="fu">predict</span>(recom_model, novos_passageiros_ratings, <span class="at">n =</span> <span class="dv">5</span>)</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspecionar as recomendações para ambos os passageiros</span></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a><span class="fu">as</span>(recommendations, <span class="st">"list"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`0`
[1] "VIP=False"              "Spa_cat=Baixo"          "ShoppingMall_cat=Baixo"
[4] "VRDeck_cat=Baixo"       "CabinDeck=G"           

$`1`
[1] "RoomService_cat=Baixo"  "FoodCourt_cat=Baixo"    "ShoppingMall_cat=Baixo"
[4] "Spa_cat=Baixo"          "VRDeck_cat=Baixo"      </code></pre>
</div>
</div>
<p>O resultado será uma lista de “recomendações” para cada um deles. Com base nas regras de associação que descobrimos, o sistema nos dirá qual item é o mais provável para cada perfil. Isso fecha o ciclo do nosso projeto, mostrando como a mineração de dados pode se traduzir em um sistema prático e preditivo.</p>
<section id="análise-das-recomendações" class="level3">
<h3 class="anchored" data-anchor-id="análise-das-recomendações">Análise das Recomendações</h3>
<p>O <em>output</em> está em formato de lista, onde cada item (<code>$0</code> e <code>$1</code>) corresponde a uma recomendação para um passageiro. A ordem das recomendações corresponde à ordem dos passageiros na matriz de entrada.</p>
<ol type="1">
<li>Recomendação para o Primeiro Passageiro (<code>$0</code>): O modelo “recomendou” a seguinte lista de itens:</li>
</ol>
<p><code>"VIP=False" "Spa_cat=Baixo" "ShoppingMall_cat=Baixo" "VRDeck_cat=Baixo" "CabinDeck=G"</code></p>
<ul>
<li><p><strong>O que o sistema viu:</strong> Se o seu primeiro passageiro era o que vinha da Terra com gastos baixos (<code>RoomService</code>, <code>FoodCourt</code>, etc.), o modelo identificou as regras que se aplicam a esse perfil.</p></li>
<li><p><strong>O que o sistema recomendou:</strong> O sistema listou os itens que, com base nas regras, estão mais fortemente associados a esse perfil. A recomendação mais importante aqui é <code>CabinDeck=G</code>. O sistema está basicamente dizendo: “Com base nas características desse passageiro (vindo da Terra, gastos baixos), a cabine mais provável para ele é no Deck G.” Os outros itens na lista são parte das regras que levaram a essa conclusão.</p></li>
</ul>
<ol start="2" type="1">
<li>Recomendação para o Segundo Passageiro ($1): O modelo “recomendou” a seguinte lista de itens:</li>
</ol>
<p><code>"RoomService_cat=Baixo" "FoodCourt_cat=Baixo" "ShoppingMall_cat=Baixo" "Spa_cat=Baixo" "VRDeck_cat=Baixo"</code></p>
<ul>
<li><p><strong>O que o sistema viu:</strong> Se o seu segundo passageiro era o VIP, adulto e em sono criogênico, a recomendação nos dá um insight diferente.</p></li>
<li><p><strong>O que o sistema recomendou:</strong> A recomendação principal aqui é uma lista de itens que representam gastos baixos. Isso faz sentido, pois nossa análise anterior mostrou que a variável <code>CryoSleep=True</code> (sono criogênico) está quase sempre associada a gastos nulos ou baixos em todos os serviços. O sistema está recomendando a previsão de que, se o passageiro está em sono criogênico, ele provavelmente terá gastos baixos nesses serviços.</p></li>
</ul>
</section>
<section id="conclusão" class="level3">
<h3 class="anchored" data-anchor-id="conclusão">Conclusão</h3>
<p>O sistema de recomendação funcionou como esperado, aplicando as regras de associação para fazer previsões lógicas para cada perfil de passageiro.</p>
<ul>
<li><p>Para o primeiro passageiro, a recomendação foi sobre a alocação da cabine.</p></li>
<li><p>Para o segundo passageiro, a recomendação foi sobre o comportamento de gastos, que é um item fortemente associado ao estado de sono criogênico.</p></li>
</ul>
<p>Isso demonstra como um sistema baseado em regras de associação pode ser usado para inferir diferentes tipos de informações com base nos padrões encontrados nos dados.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("http:\/\/professortp\.com\.br\/est1125\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2025, Tiago Pereira</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/tiagomartin/est125/edit/main/analise_dados/space_titanic_regras.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/tiagomartin/est125/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Página construída usando <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>